/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Read-only handle on a `usvg::ClipPath`. */
export declare class ClipPath {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Clip path transform.
   *
   * `transform` in SVG.
   */
  transform(): Matrix
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only handle on a `usvg::filter::Filter`. */
export declare class Filter {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Filter region.
   *
   * `x`, `y`, `width` and `height` in the SVG.
   */
  rect(): BBox
  /** A list of filter primitives. */
  primitives(): Array<Primitive>
}

/** Opaque wrapper over `fontdb::Database` (memory-mapped faces, no JSON form). */
export declare class FontDatabase {
  /**
   * Which face this database would pick for a CSS font request.
   *
   * Decision, not a derivation: `fontdb::Query` borrows a `&[Family]`
   * whose `Name` variant holds a `&str`, so it cannot be rebuilt from a
   * JS object. The request is taken apart into plain arguments instead;
   * `serif`, `sans-serif`, `cursive`, `fantasy` and `monospace` are
   * understood as the generic families.
   */
  query(families: Array<string>, weight?: number | undefined | null, italic?: boolean | undefined | null): FontFace | null
  /**
   * Raw bytes of a face, by PostScript name (see `faces()`).
   *
   * Decision, not a derivation: upstream exposes this through
   * `with_face_data<P: FnOnce(&[u8], u32) -> T>` plus an opaque `ID`.
   * Neither a closure nor that key crosses to JS, so the lookup key is
   * the PostScript name and the bytes are copied out.
   */
  faceData(postScriptName: string): Buffer | null
  constructor()
  /**
   * Loads a font data into the `Database`.
   *
   * Will load all font faces in case of a font collection.
   */
  loadFontData(data: Buffer): void
  /**
   * Loads a font file into the `Database`.
   *
   * Will load all font faces in case of a font collection.
   */
  loadFontFile(path: string): void
  /**
   * Loads font files from the selected directory into the `Database`.
   *
   * This method will scan directories recursively.
   *
   * Will load `ttf`, `otf`, `ttc` and `otc` fonts.
   *
   * Unlike other `load_*` methods, this one doesn't return an error.
   * It will simply skip malformed fonts and will print a warning into the log for each of them.
   */
  loadFontsDir(dir: string): void
  /**
   * Attempts to load system fonts.
   *
   * Supports Windows, Linux and macOS.
   *
   * System fonts loading is a surprisingly complicated task,
   * mostly unsolvable without interacting with system libraries.
   * And since `fontdb` tries to be small and portable, this method
   * will simply scan some predefined directories.
   * Which means that fonts that are not in those directories must
   * be added manually.
   */
  loadSystemFonts(): void
  /**
   * Removes a font face by `id` from the database.
   *
   * Returns `false` while attempting to remove a non-existing font face.
   *
   * Useful when you want to ignore some specific font face(s)
   * after loading a large directory with fonts.
   * Or a specific face from a font.
   */
  removeFace(id: FontFace): void
  /** Returns `true` if the `Database` contains no font faces. */
  isEmpty(): boolean
  /**
   * Returns the number of font faces in the `Database`.
   *
   * Note that `Database` stores font faces, not fonts.
   * For example, if a caller will try to load a font collection (`*.ttc`) that contains 5 faces,
   * then the `Database` will load 5 font faces and this method will return 5, not 1.
   */
  len(): number
  /** Sets the family that will be used by `Family::Serif`. */
  setSerifFamily(family: string): void
  /** Sets the family that will be used by `Family::SansSerif`. */
  setSansSerifFamily(family: string): void
  /** Sets the family that will be used by `Family::Cursive`. */
  setCursiveFamily(family: string): void
  /** Sets the family that will be used by `Family::Fantasy`. */
  setFantasyFamily(family: string): void
  /** Sets the family that will be used by `Family::Monospace`. */
  setMonospaceFamily(family: string): void
  /**
   * Returns an iterator over the internal storage.
   *
   * This can be used for manual font matching.
   */
  faces(): Array<FontFace>
  /**
   * Selects a `FaceInfo` by `id`.
   *
   * Returns `None` if a face with such ID was already removed,
   * or this ID belong to the other `Database`.
   */
  face(id: FontFace): FontFace | null
  /**
   * Transfers ownership of shared font data back to the font database. This is the reverse operation
   * of [`Self::make_shared_face_data`]. If the font data belonging to the specified face is mapped
   * from a file on disk, then that mapping is closed and the data becomes private to the process again.
   */
  makeFaceDataUnshared(id: FontFace): void
}

/** Read-only view of a `FaceInfo`. */
export declare class FontFace {
  get index(): number
  get postScriptName(): string
  get weight(): number
  get monospaced(): boolean
  /** Family names of this face, English (US) first when present. */
  get families(): Array<string>
}

/** Read-only handle on a `usvg::LinearGradient`. */
export declare class LinearGradient {
  /** `x1` coordinate. */
  x1(): number
  /** `y1` coordinate. */
  y1(): number
  /** `x2` coordinate. */
  x2(): number
  /** `y2` coordinate. */
  y2(): number
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Gradient transform.
   *
   * `gradientTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Gradient spreading method.
   *
   * `spreadMethod` in SVG.
   */
  spreadMethod(): SpreadMethod
  /** A list of `stop` elements. */
  stops(): Array<Stop>
}

/** Read-only handle on a `usvg::Mask`. */
export declare class Mask {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Mask rectangle.
   *
   * `x`, `y`, `width` and `height` in SVG.
   */
  rect(): BBox
  /**
   * Mask type.
   *
   * `mask-type` in SVG.
   */
  kind(): MaskType
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only handle on a `usvg::Pattern`. */
export declare class Pattern {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Pattern transform.
   *
   * `patternTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Pattern rectangle.
   *
   * `x`, `y`, `width` and `height` in SVG.
   */
  rect(): BBox
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only view of a `Primitive`. */
export declare class Primitive {
  get rect(): BBox
  get colorInterpolation(): ColorInterpolation
  get result(): string
}

/** Read-only handle on a `usvg::RadialGradient`. */
export declare class RadialGradient {
  /** `cx` coordinate. */
  cx(): number
  /** `cy` coordinate. */
  cy(): number
  /** Gradient radius. */
  r(): number
  /** `fx` coordinate. */
  fx(): number
  /** `fy` coordinate. */
  fy(): number
  /** Focal radius. */
  fr(): number
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Gradient transform.
   *
   * `gradientTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Gradient spreading method.
   *
   * `spreadMethod` in SVG.
   */
  spreadMethod(): SpreadMethod
  /** A list of `stop` elements. */
  stops(): Array<Stop>
}

/**
 * A parsed SVG, ready to be rendered any number of times.
 *
 * `Clone` because an async twin captures the receiver: every field is
 * behind an `Arc` or cheap to copy, so the clone is a refcount bump and
 * the worker thread never touches the JS heap.
 */
export declare class Resvg {
  constructor(svg: string | Buffer, options?: RenderOptions | undefined | null, fonts?: FontDatabase | undefined | null, images?: Record<string, Buffer> | undefined | null)
  /**
   * Hrefs of `<image>` elements that neither the supplied buffers nor the
   * filesystem could resolve. Feed them back with `resolveImage`.
   */
  pendingImages(): Array<string>
  /**
   * Named font families requested by `<text>` that the database does not
   * carry, so the text was rendered with a fallback face. Load them with
   * `FontDatabase` and re-parse to fix the output.
   */
  pendingFonts(): Array<string>
  /**
   * Supplies one image and re-parses the document.
   *
   * Pass everything you already have through the constructor's `images`
   * argument instead: this re-parses once per call.
   */
  resolveImage(href: string, data: Buffer): void
  get width(): number
  get height(): number
  /** Renders to a PNG buffer. */
  renderPng(params?: RenderParams | undefined | null): Buffer
  /**
   * Parses on a worker thread. Same arguments as the constructor, and the
   * resolved instance still reports `pendingImages` / `pendingFonts`.
   */
  static parseAsync(svg: string | Buffer, options?: RenderOptions | undefined | null, fonts?: FontDatabase | undefined | null, images?: Record<string, Buffer> | undefined | null, signal?: AbortSignal | undefined | null): Promise<Resvg>
  /**
   * Bounding box of one element, by `id`, as it will be rendered
   * (contours, filters and transforms included). `null` if there is no
   * such id or the element has no visible size.
   */
  nodeBbox(id: string): BBox | null
  /**
   * Renders a single element, by `id`, into its own PNG -- the output is
   * sized to that element, not to the document. Useful to slice an icon
   * out of a sprite sheet.
   */
  renderNodePng(id: string, params?: RenderParams | undefined | null): Buffer
  /** Handle on one element, by `id`. */
  node(id: string): SvgNode | null
  /** Direct children of the root group. */
  children(): Array<SvgNode>
  /**
   * Image size.
   *
   * Size of an image that should be created to fit the SVG.
   *
   * `width` and `height` in SVG.
   *
   * Note that this does not necessarily represent the bounding box of the
   * rendered contents. Use
   * [`self.root().abs_layer_bounding_box()`](Group::abs_layer_bounding_box)
   * to retrieve it instead.
   */
  size(): Dimensions
  /** Checks if the current tree has any text nodes. */
  hasTextNodes(): boolean
  /** Checks if the current tree has any `defs` nodes. */
  hasDefsNodes(): boolean
  /** Returns a list of all unique [`LinearGradient`]s in the tree. */
  linearGradients(): Array<LinearGradient>
  /** Returns a list of all unique [`RadialGradient`]s in the tree. */
  radialGradients(): Array<RadialGradient>
  /** Returns a list of all unique [`Pattern`]s in the tree. */
  patterns(): Array<Pattern>
  /** Returns a list of all unique [`ClipPath`]s in the tree. */
  clipPaths(): Array<ClipPath>
  /** Returns a list of all unique [`Mask`]s in the tree. */
  masks(): Array<Mask>
  /** Returns a list of all unique [`Filter`](filter::Filter)s in the tree. */
  filters(): Array<Filter>
  /** Returns the font database that applies to all text nodes in the tree. */
  fontdb(): FontDatabase
  /**
   * Element's transform.
   *
   * This is a relative transform. The one that is set via the `transform` attribute in SVG.
   */
  transform(): Matrix
  /**
   * Element's absolute transform.
   *
   * Contains all ancestors transforms including group's transform.
   *
   * Note that subroots, like clipPaths, masks and patterns, have their own root transform,
   * which isn't affected by the node that references this subroot.
   */
  absTransform(): Matrix
  /**
   * Group opacity.
   *
   * After the group is rendered we should combine
   * it with a parent group using the specified opacity.
   */
  opacity(): number
  /**
   * Group blend mode.
   *
   * `mix-blend-mode` in SVG.
   */
  blendMode(): BlendMode
  /**
   * Element's object bounding box.
   *
   * `objectBoundingBox` in SVG terms. Meaning it doesn't affected by parent transforms.
   *
   * Can be set to `None` in case of an empty group.
   */
  boundingBox(): BBox
  /**
   * Element's bounding box in canvas coordinates.
   *
   * `userSpaceOnUse` in SVG terms.
   */
  absBoundingBox(): BBox
  /**
   * Element's object bounding box including stroke.
   *
   * Similar to `bounding_box`, but includes stroke.
   */
  strokeBoundingBox(): BBox
  /**
   * Element's bounding box including stroke in user coordinates.
   *
   * Similar to `abs_bounding_box`, but includes stroke.
   */
  absStrokeBoundingBox(): BBox
  /**
   * Element's "layer" bounding box in object units.
   *
   * Conceptually, this is `stroke_bounding_box` expanded and/or clipped
   * by `filters_bounding_box`, but also including all the children.
   * This is the bounding box `resvg` will later use to allocate layers/pixmaps
   * during isolated groups rendering.
   *
   * Only groups have it, because only groups can have filters.
   * For other nodes layer bounding box is the same as stroke bounding box.
   *
   * Unlike other bounding boxes, cannot have zero size.
   *
   * Returns 0x0x1x1 for empty groups.
   */
  layerBoundingBox(): BBox
  /** Element's "layer" bounding box in canvas units. */
  absLayerBoundingBox(): BBox
  /** Returns `true` if the group has any children. */
  hasChildren(): boolean
  /**
   * Calculates a node's filter bounding box.
   *
   * Filters with `objectBoundingBox` and missing or zero `bounding_box` would be ignored.
   *
   * Note that a filter region can act like a clipping rectangle,
   * therefore this function can produce a bounding box smaller than `bounding_box`.
   *
   * Returns `None` when then group has no filters.
   *
   * This function is very fast, that's why we do not store this bbox as a `Group` field.
   */
  filtersBoundingBox(): BBox | null
  /**
   * Writes the parsed tree back out as a usvg-simplified SVG string.
   *
   * Text is converted to paths unless `preserveText` is set.
   */
  toString(options?: WriteOptions | undefined | null): string
  /** Renders to raw RGBA8 pixels. */
  renderRaw(params?: RenderParams | undefined | null): RawImage
  /** `renderPng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderPngAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /** `renderNodePng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderNodePngAsync(id: string, params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /** `toString` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  toStringAsync(options?: WriteOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<string>
  /** `renderRaw` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderRawAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<RawImage>
}

/**
 * A read-only handle on one element of the parsed tree.
 *
 * usvg stores nodes as `Box`, not `Arc`, so a handle cannot own one. It
 * keeps the tree alive plus the child-index path instead, and re-resolves
 * on each call -- safe because a parsed tree is immutable.
 */
export declare class SvgNode {
  /** `group`, `path`, `image` or `text`. */
  get kind(): NodeKind
  /** Direct children. Empty for anything that is not a group. */
  children(): Array<SvgNode>
  /**
   * Extent of this element's own filters, if it is a filtered group.
   * This is what the document-level `filtersBoundingBox()` cannot see:
   * usvg wraps every filtered element in an inner group.
   */
  filtersBbox(): BBox | null
  /**
   * Extent this element will actually occupy once rendered, contours and
   * filters included.
   */
  extent(): BBox | null
  /**
   * Clip path applied to this element, if it is a clipped group.
   *
   * usvg hands out a bare `&ClipPath` here, with no `Arc` to hold on to,
   * so it is matched by `id` against the document's clip-path table.
   * Returns `null` for an unnamed clip path.
   */
  clipPath(): ClipPath | null
  /** Mask applied to this element, matched by `id` like `clipPath`. */
  mask(): Mask | null
  /** Renders this element alone, sized to its own extent. */
  renderPng(params?: RenderParams | undefined | null): Buffer
  /** Returns node's ID. */
  id(): string
  /**
   * Returns node's absolute transform.
   *
   * This method is cheap since absolute transforms are already resolved.
   */
  absTransform(): Matrix
  /** Returns node's bounding box in object coordinates, if any. */
  boundingBox(): BBox
  /** Returns node's bounding box in canvas coordinates, if any. */
  absBoundingBox(): BBox
  /** Returns node's bounding box, including stroke, in object coordinates, if any. */
  strokeBoundingBox(): BBox
  /** Returns node's bounding box, including stroke, in canvas coordinates, if any. */
  absStrokeBoundingBox(): BBox
  /**
   * Element's "layer" bounding box in canvas units, if any.
   *
   * For most nodes this is just `abs_bounding_box`,
   * but for groups this is `abs_layer_bounding_box`.
   *
   * See [`Group::layer_bounding_box`] for details.
   */
  absLayerBoundingBox(): BBox | null
  /** `renderPng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderPngAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
}

/** An alignment baseline property. */
export declare const enum AlignmentBaseline {
  Auto = 'auto',
  Baseline = 'baseline',
  BeforeEdge = 'beforeEdge',
  TextBeforeEdge = 'textBeforeEdge',
  Middle = 'middle',
  Central = 'central',
  AfterEdge = 'afterEdge',
  TextAfterEdge = 'textAfterEdge',
  Ideographic = 'ideographic',
  Alphabetic = 'alphabetic',
  Hanging = 'hanging',
  Mathematical = 'mathematical'
}

/** A rectangle in SVG user units. */
export interface BBox {
  x: number
  y: number
  width: number
  height: number
}

/**
 * A blending mode property.
 *
 * `mix-blend-mode` attribute in the SVG.
 */
export declare const enum BlendMode {
  Normal = 'normal',
  Multiply = 'multiply',
  Screen = 'screen',
  Overlay = 'overlay',
  Darken = 'darken',
  Lighten = 'lighten',
  ColorDodge = 'colorDodge',
  ColorBurn = 'colorBurn',
  HardLight = 'hardLight',
  SoftLight = 'softLight',
  Difference = 'difference',
  Exclusion = 'exclusion',
  Hue = 'hue',
  Saturation = 'saturation',
  Color = 'color',
  Luminosity = 'luminosity'
}

/** Plain view of a `Color`. */
export interface Color {
  red: number
  green: number
  blue: number
}

/** A color channel. */
export declare const enum ColorChannel {
  R = 'r',
  G = 'g',
  B = 'b',
  A = 'a'
}

/**
 * A color interpolation mode.
 *
 * The default is `ColorInterpolation::LinearRGB`.
 */
export declare const enum ColorInterpolation {
  SRGB = 'srgb',
  LinearRGB = 'linearRgb'
}

/** A width/height pair in SVG user units. */
export interface Dimensions {
  width: number
  height: number
}

/** A dominant baseline property. */
export declare const enum DominantBaseline {
  Auto = 'auto',
  UseScript = 'useScript',
  NoChange = 'noChange',
  ResetSize = 'resetSize',
  Ideographic = 'ideographic',
  Alphabetic = 'alphabetic',
  Hanging = 'hanging',
  Mathematical = 'mathematical',
  Central = 'central',
  Middle = 'middle',
  TextAfterEdge = 'textAfterEdge',
  TextBeforeEdge = 'textBeforeEdge'
}

/** An edges processing mode. */
export declare const enum EdgeMode {
  None = 'none',
  Duplicate = 'duplicate',
  Wrap = 'wrap'
}

/**
 * A fill rule.
 *
 * `fill-rule` attribute in the SVG.
 */
export declare const enum FillRule {
  NonZero = 'nonZero',
  EvenOdd = 'evenOdd'
}

/**
 * A font optical sizing property.
 *
 * Controls automatic adjustment of the `opsz` axis in variable fonts
 * based on font size. Matches CSS `font-optical-sizing`.
 */
export declare const enum FontOpticalSizing {
  Auto = 'auto',
  None = 'none'
}

/** A font stretch property. */
export declare const enum FontStretch {
  UltraCondensed = 'ultraCondensed',
  ExtraCondensed = 'extraCondensed',
  Condensed = 'condensed',
  SemiCondensed = 'semiCondensed',
  Normal = 'normal',
  SemiExpanded = 'semiExpanded',
  Expanded = 'expanded',
  ExtraExpanded = 'extraExpanded',
  UltraExpanded = 'ultraExpanded'
}

/** A font style property. */
export declare const enum FontStyle {
  Normal = 'normal',
  Italic = 'italic',
  Oblique = 'oblique'
}

/**
 * An image rendering method.
 *
 * `image-rendering` attribute in the SVG.
 */
export declare const enum ImageRendering {
  OptimizeQuality = 'optimizeQuality',
  OptimizeSpeed = 'optimizeSpeed',
  Smooth = 'smooth',
  HighQuality = 'highQuality',
  CrispEdges = 'crispEdges',
  Pixelated = 'pixelated'
}

/** A length adjust property. */
export declare const enum LengthAdjust {
  Spacing = 'spacing',
  SpacingAndGlyphs = 'spacingAndGlyphs'
}

/**
 * A line cap.
 *
 * `stroke-linecap` attribute in the SVG.
 */
export declare const enum LineCap {
  Butt = 'butt',
  Round = 'round',
  Square = 'square'
}

/**
 * A line join.
 *
 * `stroke-linejoin` attribute in the SVG.
 */
export declare const enum LineJoin {
  Miter = 'miter',
  MiterClip = 'miterClip',
  Round = 'round',
  Bevel = 'bevel'
}

/** A mask type. */
export declare const enum MaskType {
  Luminance = 'luminance',
  Alpha = 'alpha'
}

/** An affine transform, same field order as SVG's `matrix(...)`. */
export interface Matrix {
  sx: number
  kx: number
  ky: number
  sy: number
  tx: number
  ty: number
}

/** A morphology operation. */
export declare const enum MorphologyOperator {
  Erode = 'erode',
  Dilate = 'dilate'
}

/** Which flavour of node this is. */
export declare const enum NodeKind {
  Group = 'group',
  Path = 'path',
  Image = 'image',
  Text = 'text'
}

/**
 * Representation of the [`paint-order`] property.
 *
 * `usvg` will handle `markers` automatically,
 * therefore we provide only `fill` and `stroke` variants.
 *
 * [`paint-order`]: https://www.w3.org/TR/SVG2/painting.html#PaintOrder
 */
export declare const enum PaintOrder {
  FillAndStroke = 'fillAndStroke',
  StrokeAndFill = 'strokeAndFill'
}

/** Un-premultiplied RGBA8 pixels, row-major, no padding. */
export interface RawImage {
  width: number
  height: number
  data: Buffer
}

/**
 * One-shot: parse and render a PNG entirely off the event loop.
 *
 * Uses the process-wide system font database and resolves images off the
 * filesystem only. For a custom `FontDatabase`, supplied image buffers or
 * the `pendingImages` / `pendingFonts` reports, use `Resvg.parseAsync`.
 */
export declare function renderAsync(svg: string | Buffer, options?: RenderOptions | undefined | null, params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>

/**
 * Mirror of `usvg::Options`. Every field is optional; omitted fields
 * keep the usvg default.
 */
export interface RenderOptions {
  /**
   * Directory that will be used during relative paths resolving.
   *
   * Expected to be the same as the directory that contains the SVG file,
   * but can be set to any.
   *
   * Default: `None`
   */
  resourcesDir?: string
  /**
   * Target DPI.
   *
   * Impacts units conversion.
   *
   * Default: 96.0
   */
  dpi?: number
  /**
   * A default font family.
   *
   * Will be used when no `font-family` attribute is set in the SVG.
   *
   * Default: Times New Roman
   */
  fontFamily?: string
  /**
   * A default font size.
   *
   * Will be used when no `font-size` attribute is set in the SVG.
   *
   * Default: 12
   */
  fontSize?: number
  /**
   * A list of languages.
   *
   * Will be used to resolve a `systemLanguage` conditional attribute.
   *
   * Format: en, en-US.
   *
   * Default: `[en]`
   */
  languages?: Array<string>
  /**
   * Specifies the default shape rendering method.
   *
   * Will be used when an SVG element's `shape-rendering` property is set to `auto`.
   *
   * Default: GeometricPrecision
   */
  shapeRendering?: ShapeRendering
  /**
   * Specifies the default text rendering method.
   *
   * Will be used when an SVG element's `text-rendering` property is set to `auto`.
   *
   * Default: OptimizeLegibility
   */
  textRendering?: TextRendering
  /**
   * Specifies the default image rendering method.
   *
   * Will be used when an SVG element's `image-rendering` property is set to `auto`.
   *
   * Default: OptimizeQuality
   */
  imageRendering?: ImageRendering
  /**
   * Default viewport size to assume if there is no `viewBox` attribute and
   * the `width` or `height` attributes are relative.
   *
   * Default: `(100, 100)`
   */
  defaultSizeWidth?: number
  /**
   * Default viewport size to assume if there is no `viewBox` attribute and
   * the `width` or `height` attributes are relative.
   *
   * Default: `(100, 100)`
   */
  defaultSizeHeight?: number
  /**
   * A CSS stylesheet that should be injected into the SVG. Can be used to overwrite
   * certain attributes.
   */
  styleSheet?: string
}

/** Output size / scaling of one render pass. */
export interface RenderParams {
  /** Uniform scale factor. Default: 1. */
  scale?: number
  /** Target width in px; keeps the aspect ratio and overrides `scale`. */
  width?: number
  /** Target height in px; keeps the aspect ratio and overrides `scale`. */
  height?: number
  /**
   * Background colour: any CSS3 colour string, e.g. `#eee`, `teal`,
   * `rgba(255, 0, 0, .5)`. Default: transparent.
   */
  background?: string
  /**
   * Render only this rectangle, in SVG user units. `scale` / `width` /
   * `height` then size the crop, not the full viewport. Feed it
   * `absLayerBoundingBox()` to trim the document to its content.
   */
  crop?: BBox
}

/**
 * Starts collecting what usvg and resvg report.
 *
 * `level` is `off`, `error`, `warn`, `info`, `debug` or `trace`. Safe to
 * call repeatedly: the logger is installed once, the level always applies.
 */
export declare function setLogLevel(level: string): void

/**
 * A shape rendering method.
 *
 * `shape-rendering` attribute in the SVG.
 */
export declare const enum ShapeRendering {
  OptimizeSpeed = 'optimizeSpeed',
  CrispEdges = 'crispEdges',
  GeometricPrecision = 'geometricPrecision'
}

/**
 * A spread method.
 *
 * `spreadMethod` attribute in the SVG.
 */
export declare const enum SpreadMethod {
  Pad = 'pad',
  Reflect = 'reflect',
  Repeat = 'repeat'
}

/** Plain view of a `Stop`. */
export interface Stop {
  offset: number
  color: Color
  opacity: number
}

/** Drains the messages collected since the last call. */
export declare function takeLogs(): Array<string>

/** A text chunk anchor property. */
export declare const enum TextAnchor {
  Start = 'start',
  Middle = 'middle',
  End = 'end'
}

/**
 * A text rendering method.
 *
 * `text-rendering` attribute in the SVG.
 */
export declare const enum TextRendering {
  OptimizeSpeed = 'optimizeSpeed',
  OptimizeLegibility = 'optimizeLegibility',
  GeometricPrecision = 'geometricPrecision'
}

/** A turbulence kind for the `feTurbulence` filter. */
export declare const enum TurbulenceKind {
  FractalNoise = 'fractalNoise',
  Turbulence = 'turbulence'
}

/**
 * Mirror of `usvg::WriteOptions`, for `Resvg.toString()`. Every field is
 * optional; omitted fields keep the usvg default.
 */
export interface WriteOptions {
  /** Used to add a custom prefix to each element ID during writing. */
  idPrefix?: string
  /**
   * Do not convert text into paths.
   *
   * Default: false
   */
  preserveText?: boolean
  /**
   * Set the coordinates numeric precision.
   *
   * Smaller precision can lead to a malformed output in some cases.
   *
   * Default: 8
   */
  coordinatesPrecision?: number
  /**
   * Set the transform values numeric precision.
   *
   * Smaller precision can lead to a malformed output in some cases.
   *
   * Default: 8
   */
  transformsPrecision?: number
  /**
   * Use single quote marks instead of double quote.
   *
   * # Examples
   *
   * Before:
   *
   * ```text
   * <rect fill="red"/>
   * ```
   *
   * After:
   *
   * ```text
   * <rect fill='red'/>
   * ```
   *
   * Default: disabled
   */
  useSingleQuote?: boolean
}

/** A writing mode. */
export declare const enum WritingMode {
  LeftToRight = 'leftToRight',
  TopToBottom = 'topToBottom'
}
