/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Read-only handle on a `usvg::ClipPath`. */
export declare class ClipPath {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Clip path transform.
   *
   * `transform` in SVG.
   */
  transform(): Matrix
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only handle on a `usvg::filter::Filter`. */
export declare class Filter {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Filter region.
   *
   * `x`, `y`, `width` and `height` in the SVG.
   */
  rect(): BBox
  /** A list of filter primitives. */
  primitives(): Array<Primitive>
}

/** Read-only view of a `Font`. */
export declare class Font {
  get style(): FontStyle
  get stretch(): FontStretch
  get weight(): number
  get variations(): Array<FontVariation>
}

/** Opaque wrapper over `fontdb::Database` (memory-mapped faces, no JSON form). */
export declare class FontDatabase {
  /**
   * Which face this database would pick for a CSS font request.
   *
   * Decision, not a derivation: `fontdb::Query` borrows a `&[Family]`
   * whose `Name` variant holds a `&str`, so it cannot be rebuilt from a
   * JS object. The request is taken apart into plain arguments instead;
   * `serif`, `sans-serif`, `cursive`, `fantasy` and `monospace` are
   * understood as the generic families.
   */
  query(families: Array<string>, weight?: number | undefined | null, italic?: boolean | undefined | null): FontFace | null
  /**
   * Raw bytes of a face, by PostScript name (see `faces()`).
   *
   * Decision, not a derivation: upstream exposes this through
   * `with_face_data<P: FnOnce(&[u8], u32) -> T>` plus an opaque `ID`.
   * Neither a closure nor that key crosses to JS, so the lookup key is
   * the PostScript name and the bytes are copied out.
   */
  faceData(postScriptName: string): Buffer | null
  constructor()
  /**
   * Loads a font data into the `Database`.
   *
   * Will load all font faces in case of a font collection.
   */
  loadFontData(data: Buffer): void
  /**
   * Loads a font file into the `Database`.
   *
   * Will load all font faces in case of a font collection.
   */
  loadFontFile(path: string): void
  /**
   * Loads font files from the selected directory into the `Database`.
   *
   * This method will scan directories recursively.
   *
   * Will load `ttf`, `otf`, `ttc` and `otc` fonts.
   *
   * Unlike other `load_*` methods, this one doesn't return an error.
   * It will simply skip malformed fonts and will print a warning into the log for each of them.
   */
  loadFontsDir(dir: string): void
  /**
   * Attempts to load system fonts.
   *
   * Supports Windows, Linux and macOS.
   *
   * System fonts loading is a surprisingly complicated task,
   * mostly unsolvable without interacting with system libraries.
   * And since `fontdb` tries to be small and portable, this method
   * will simply scan some predefined directories.
   * Which means that fonts that are not in those directories must
   * be added manually.
   */
  loadSystemFonts(): void
  /**
   * Removes a font face by `id` from the database.
   *
   * Returns `false` while attempting to remove a non-existing font face.
   *
   * Useful when you want to ignore some specific font face(s)
   * after loading a large directory with fonts.
   * Or a specific face from a font.
   */
  removeFace(id: FontFace): void
  /** Returns `true` if the `Database` contains no font faces. */
  isEmpty(): boolean
  /**
   * Returns the number of font faces in the `Database`.
   *
   * Note that `Database` stores font faces, not fonts.
   * For example, if a caller will try to load a font collection (`*.ttc`) that contains 5 faces,
   * then the `Database` will load 5 font faces and this method will return 5, not 1.
   */
  len(): number
  /** Sets the family that will be used by `Family::Serif`. */
  setSerifFamily(family: string): void
  /** Sets the family that will be used by `Family::SansSerif`. */
  setSansSerifFamily(family: string): void
  /** Sets the family that will be used by `Family::Cursive`. */
  setCursiveFamily(family: string): void
  /** Sets the family that will be used by `Family::Fantasy`. */
  setFantasyFamily(family: string): void
  /** Sets the family that will be used by `Family::Monospace`. */
  setMonospaceFamily(family: string): void
  /**
   * Returns an iterator over the internal storage.
   *
   * This can be used for manual font matching.
   */
  faces(): Array<FontFace>
  /**
   * Selects a `FaceInfo` by `id`.
   *
   * Returns `None` if a face with such ID was already removed,
   * or this ID belong to the other `Database`.
   */
  face(id: FontFace): FontFace | null
  /**
   * Transfers ownership of shared font data back to the font database. This is the reverse operation
   * of [`Self::make_shared_face_data`]. If the font data belonging to the specified face is mapped
   * from a file on disk, then that mapping is closed and the data becomes private to the process again.
   */
  makeFaceDataUnshared(id: FontFace): void
}

/** Read-only view of a `FaceInfo`. */
export declare class FontFace {
  get index(): number
  get postScriptName(): String
  get style(): FontFaceStyle
  get weight(): number
  get monospaced(): boolean
  /** Family names of this face, English (US) first when present. */
  get families(): Array<string>
}

/** Read-only view of an `Image`. */
export declare class Image {
  get id(): String
  get isVisible(): boolean
  get renderingMode(): ImageRendering
  get kind(): ImageKindJpeg | ImageKindPng | ImageKindGif | ImageKindWebp | ImageKindSvg
  get absTransform(): Matrix
  get boundingBox(): BBox
  get absBoundingBox(): BBox
}

/** `ImageKind::GIF`. The bytes are the document's own. */
export declare class ImageKindGif {
  /** Discriminant. Narrow on this. */
  get type(): 'gif'
  /** The encoded bytes, exactly as the document supplied them: usvg does not decode them, and neither does this. */
  get bytes(): Buffer
}

/** `ImageKind::JPEG`. The bytes are the document's own. */
export declare class ImageKindJpeg {
  /** Discriminant. Narrow on this. */
  get type(): 'jpeg'
  /** The encoded bytes, exactly as the document supplied them: usvg does not decode them, and neither does this. */
  get bytes(): Buffer
}

/** `ImageKind::PNG`. The bytes are the document's own. */
export declare class ImageKindPng {
  /** Discriminant. Narrow on this. */
  get type(): 'png'
  /** The encoded bytes, exactly as the document supplied them: usvg does not decode them, and neither does this. */
  get bytes(): Buffer
}

/** `ImageKind::WEBP`. The bytes are the document's own. */
export declare class ImageKindWebp {
  /** Discriminant. Narrow on this. */
  get type(): 'webp'
  /** The encoded bytes, exactly as the document supplied them: usvg does not decode them, and neither does this. */
  get bytes(): Buffer
}

/** Read-only handle on a `usvg::LinearGradient`. */
export declare class LinearGradient {
  /** `x1` coordinate. */
  x1(): number
  /** `y1` coordinate. */
  y1(): number
  /** `x2` coordinate. */
  x2(): number
  /** `y2` coordinate. */
  y2(): number
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Gradient transform.
   *
   * `gradientTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Gradient spreading method.
   *
   * `spreadMethod` in SVG.
   */
  spreadMethod(): SpreadMethod
  /** A list of `stop` elements. */
  stops(): Array<Stop>
}

/** Read-only handle on a `usvg::Mask`. */
export declare class Mask {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Mask rectangle.
   *
   * `x`, `y`, `width` and `height` in SVG.
   */
  rect(): BBox
  /**
   * Mask type.
   *
   * `mask-type` in SVG.
   */
  kind(): MaskType
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only handle on a `usvg::Pattern`. */
export declare class Pattern {
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Pattern transform.
   *
   * `patternTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Pattern rectangle.
   *
   * `x`, `y`, `width` and `height` in SVG.
   */
  rect(): BBox
  /** Children of this definition's content group. */
  children(): Array<SvgNode>
}

/** Read-only view of a `PositionedGlyph`. */
export declare class PositionedGlyph {
  get fontSize(): number
  get transform(): Matrix
  get outlineTransform(): Matrix
  get svgTransform(): Matrix
  get colrTransform(): Matrix
  get id(): number
  get text(): String
}

/** Read-only handle on a `usvg::RadialGradient`. */
export declare class RadialGradient {
  /** `cx` coordinate. */
  cx(): number
  /** `cy` coordinate. */
  cy(): number
  /** Gradient radius. */
  r(): number
  /** `fx` coordinate. */
  fx(): number
  /** `fy` coordinate. */
  fy(): number
  /** Focal radius. */
  fr(): number
  /**
   * Element's ID.
   *
   * Taken from the SVG itself.
   * Used only during SVG writing. `resvg` doesn't rely on this property.
   */
  id(): string
  /**
   * Gradient transform.
   *
   * `gradientTransform` in SVG.
   */
  transform(): Matrix
  /**
   * Gradient spreading method.
   *
   * `spreadMethod` in SVG.
   */
  spreadMethod(): SpreadMethod
  /** A list of `stop` elements. */
  stops(): Array<Stop>
}

/**
 * A parsed SVG, ready to be rendered any number of times.
 *
 * `Clone` because an async twin captures the receiver: every field is
 * behind an `Arc` or cheap to copy, so the clone is a refcount bump and
 * the worker thread never touches the JS heap.
 */
export declare class Resvg {
  constructor(svg: string | Buffer, options?: RenderOptions | undefined | null, fonts?: FontDatabase | undefined | null, images?: Record<string, Buffer> | undefined | null)
  /**
   * Hrefs of `<image>` elements that neither the supplied buffers nor the
   * filesystem could resolve. Feed them back with `resolveImage`.
   */
  pendingImages(): Array<string>
  /**
   * Named font families requested by `<text>` that the database does not
   * carry, so the text was rendered with a fallback face. Load them with
   * `FontDatabase` and re-parse to fix the output.
   */
  pendingFonts(): Array<string>
  /**
   * Supplies one image and re-parses the document.
   *
   * Pass everything you already have through the constructor's `images`
   * argument instead: this re-parses once per call.
   */
  resolveImage(href: string, data: Buffer): void
  get width(): number
  get height(): number
  /** Renders to a PNG buffer. */
  renderPng(params?: RenderParams | undefined | null): Buffer
  /**
   * Parses on a worker thread. Same arguments as the constructor, and the
   * resolved instance still reports `pendingImages` / `pendingFonts`.
   */
  static parseAsync(svg: string | Buffer, options?: RenderOptions | undefined | null, fonts?: FontDatabase | undefined | null, images?: Record<string, Buffer> | undefined | null, signal?: AbortSignal | undefined | null): Promise<Resvg>
  /**
   * Bounding box of one element, by `id`, as it will be rendered
   * (contours, filters and transforms included). `null` if there is no
   * such id or the element has no visible size.
   */
  nodeBbox(id: string): BBox | null
  /**
   * Renders a single element, by `id`, into its own PNG -- the output is
   * sized to that element, not to the document. Useful to slice an icon
   * out of a sprite sheet.
   */
  renderNodePng(id: string, params?: RenderParams | undefined | null): Buffer
  /** Handle on one element, by `id`. */
  node(id: string): SvgNode | null
  /** Direct children of the root group. */
  children(): Array<SvgNode>
  /**
   * Image size.
   *
   * Size of an image that should be created to fit the SVG.
   *
   * `width` and `height` in SVG.
   *
   * Note that this does not necessarily represent the bounding box of the
   * rendered contents. Use
   * [`self.root().abs_layer_bounding_box()`](Group::abs_layer_bounding_box)
   * to retrieve it instead.
   */
  size(): Dimensions
  /** Checks if the current tree has any text nodes. */
  hasTextNodes(): boolean
  /** Checks if the current tree has any `defs` nodes. */
  hasDefsNodes(): boolean
  /** Returns a list of all unique [`LinearGradient`]s in the tree. */
  linearGradients(): Array<LinearGradient>
  /** Returns a list of all unique [`RadialGradient`]s in the tree. */
  radialGradients(): Array<RadialGradient>
  /** Returns a list of all unique [`Pattern`]s in the tree. */
  patterns(): Array<Pattern>
  /** Returns a list of all unique [`ClipPath`]s in the tree. */
  clipPaths(): Array<ClipPath>
  /** Returns a list of all unique [`Mask`]s in the tree. */
  masks(): Array<Mask>
  /** Returns a list of all unique [`Filter`](filter::Filter)s in the tree. */
  filters(): Array<Filter>
  /** Returns the font database that applies to all text nodes in the tree. */
  fontdb(): FontDatabase
  /**
   * Element's transform.
   *
   * This is a relative transform. The one that is set via the `transform` attribute in SVG.
   */
  transform(): Matrix
  /**
   * Element's absolute transform.
   *
   * Contains all ancestors transforms including group's transform.
   *
   * Note that subroots, like clipPaths, masks and patterns, have their own root transform,
   * which isn't affected by the node that references this subroot.
   */
  absTransform(): Matrix
  /**
   * Group opacity.
   *
   * After the group is rendered we should combine
   * it with a parent group using the specified opacity.
   */
  opacity(): number
  /**
   * Group blend mode.
   *
   * `mix-blend-mode` in SVG.
   */
  blendMode(): BlendMode
  /**
   * Element's object bounding box.
   *
   * `objectBoundingBox` in SVG terms. Meaning it doesn't affected by parent transforms.
   *
   * Can be set to `None` in case of an empty group.
   */
  boundingBox(): BBox
  /**
   * Element's bounding box in canvas coordinates.
   *
   * `userSpaceOnUse` in SVG terms.
   */
  absBoundingBox(): BBox
  /**
   * Element's object bounding box including stroke.
   *
   * Similar to `bounding_box`, but includes stroke.
   */
  strokeBoundingBox(): BBox
  /**
   * Element's bounding box including stroke in user coordinates.
   *
   * Similar to `abs_bounding_box`, but includes stroke.
   */
  absStrokeBoundingBox(): BBox
  /**
   * Element's "layer" bounding box in object units.
   *
   * Conceptually, this is `stroke_bounding_box` expanded and/or clipped
   * by `filters_bounding_box`, but also including all the children.
   * This is the bounding box `resvg` will later use to allocate layers/pixmaps
   * during isolated groups rendering.
   *
   * Only groups have it, because only groups can have filters.
   * For other nodes layer bounding box is the same as stroke bounding box.
   *
   * Unlike other bounding boxes, cannot have zero size.
   *
   * Returns 0x0x1x1 for empty groups.
   */
  layerBoundingBox(): BBox
  /** Element's "layer" bounding box in canvas units. */
  absLayerBoundingBox(): BBox
  /** Returns `true` if the group has any children. */
  hasChildren(): boolean
  /**
   * Calculates a node's filter bounding box.
   *
   * Filters with `objectBoundingBox` and missing or zero `bounding_box` would be ignored.
   *
   * Note that a filter region can act like a clipping rectangle,
   * therefore this function can produce a bounding box smaller than `bounding_box`.
   *
   * Returns `None` when then group has no filters.
   *
   * This function is very fast, that's why we do not store this bbox as a `Group` field.
   */
  filtersBoundingBox(): BBox | null
  /**
   * Writes the parsed tree back out as a usvg-simplified SVG string.
   *
   * Text is converted to paths unless `preserveText` is set.
   */
  toString(options?: WriteOptions | undefined | null): string
  /** Renders to raw RGBA8 pixels. */
  renderRaw(params?: RenderParams | undefined | null): RawImage
  /** `renderPng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderPngAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /** `renderNodePng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderNodePngAsync(id: string, params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /** `toString` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  toStringAsync(options?: WriteOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<string>
  /** `renderRaw` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderRawAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<RawImage>
}

/** Read-only view of a `Span`. */
export declare class Span {
  get fill(): Fill | null
  get stroke(): Stroke | null
  get paintOrder(): PaintOrder
  get fontSize(): number
  get variations(): Array<FontVariation>
  get fontOpticalSizing(): FontOpticalSizing
  get visible(): boolean
  get positionedGlyphs(): Array<PositionedGlyph>
  get underline(): Path | null
  get overline(): Path | null
  get lineThrough(): Path | null
}

/**
 * A read-only handle on one element of the parsed tree.
 *
 * usvg stores nodes as `Box`, not `Arc`, so a handle cannot own one. It
 * keeps the tree alive plus the child-index path instead, and re-resolves
 * on each call -- safe because a parsed tree is immutable.
 */
export declare class SvgNode {
  /** `group`, `path`, `image` or `text`. */
  get kind(): NodeKind
  /**
   * The laid-out content of a text node: chunks, spans, resolved
   * fonts. Null for anything that is not text.
   *
   * Its presence is what makes the text types map at all -- a node
   * payload is not a collection, so nothing else nominates them.
   */
  text(): Text | null
  /**
   * The shape of a path node: geometry, fill, stroke, paint order.
   * Null for a group, an image or a text node.
   *
   * This is what makes `Fill`, `Stroke` and `Path` reachable at all: the
   * mapper prunes any generated type no exposed method hands out.
   */
  path(): Path | null
  /**
   * The content of an image node: where it sits, how it is to
   * be scaled, and the bytes themselves. Null for anything else.
   *
   * `kind` is a discriminated union. The four raster variants
   * carry the encoded bytes exactly as the document supplied
   * them -- usvg says they should be decoded by the caller, and
   * this is the caller -- while `svg` carries none, an embedded
   * SVG being a tree rather than a payload.
   */
  image(): Image | null
  /** Direct children. Empty for anything that is not a group. */
  children(): Array<SvgNode>
  /**
   * Extent of this element's own filters, if it is a filtered group.
   * This is what the document-level `filtersBoundingBox()` cannot see:
   * usvg wraps every filtered element in an inner group.
   */
  filtersBbox(): BBox | null
  /**
   * Extent this element will actually occupy once rendered, contours and
   * filters included.
   */
  extent(): BBox | null
  /**
   * Clip path applied to this element, if it is a clipped group.
   *
   * usvg hands out a bare `&ClipPath` here, with no `Arc` to hold on to,
   * so it is matched by `id` against the document's clip-path table.
   * Returns `null` for an unnamed clip path.
   */
  clipPath(): ClipPath | null
  /** Mask applied to this element, matched by `id` like `clipPath`. */
  mask(): Mask | null
  /** Renders this element alone, sized to its own extent. */
  renderPng(params?: RenderParams | undefined | null): Buffer
  /** Returns node's ID. */
  id(): string
  /**
   * Returns node's absolute transform.
   *
   * This method is cheap since absolute transforms are already resolved.
   */
  absTransform(): Matrix
  /** Returns node's bounding box in object coordinates, if any. */
  boundingBox(): BBox
  /** Returns node's bounding box in canvas coordinates, if any. */
  absBoundingBox(): BBox
  /** Returns node's bounding box, including stroke, in object coordinates, if any. */
  strokeBoundingBox(): BBox
  /** Returns node's bounding box, including stroke, in canvas coordinates, if any. */
  absStrokeBoundingBox(): BBox
  /**
   * Element's "layer" bounding box in canvas units, if any.
   *
   * For most nodes this is just `abs_bounding_box`,
   * but for groups this is `abs_layer_bounding_box`.
   *
   * See [`Group::layer_bounding_box`] for details.
   */
  absLayerBoundingBox(): BBox | null
  /** `renderPng` on a worker thread: the work leaves the event loop, and a
  queued call is dropped when the signal fires. */
  renderPngAsync(params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>
}

/** Read-only view of a `Text`. */
export declare class Text {
  get id(): String
  get renderingMode(): TextRendering
  get dx(): Array<number>
  get dy(): Array<number>
  get rotate(): Array<number>
  get writingMode(): WritingMode
  get chunks(): Array<TextChunk>
  get absTransform(): Matrix
  get boundingBox(): BBox
  get absBoundingBox(): BBox
  get strokeBoundingBox(): BBox
  get absStrokeBoundingBox(): BBox
  get layouted(): Array<Span>
}

/** Read-only view of a `TextChunk`. */
export declare class TextChunk {
  get x(): number | null
  get y(): number | null
  get anchor(): TextAnchor
  get spans(): Array<TextSpan>
  get textFlow(): TextFlowPlain | TextFlowPath
  get text(): String
}

/** Read-only view of a `TextSpan`. */
export declare class TextSpan {
  get start(): number
  get end(): number
  get fill(): Fill | null
  get stroke(): Stroke | null
  get paintOrder(): PaintOrder
  get font(): Font
  get fontSize(): number
  get smallCaps(): boolean
  get applyKerning(): boolean
  get fontOpticalSizing(): FontOpticalSizing
  get decoration(): TextDecoration
  get dominantBaseline(): DominantBaseline
  get alignmentBaseline(): AlignmentBaseline
  get baselineShift(): Array<BaselineShiftPlain | BaselineShiftNumber>
  get isVisible(): boolean
  get letterSpacing(): number
  get wordSpacing(): number
  get textLength(): number | null
  get lengthAdjust(): LengthAdjust
}

/** An alignment baseline property. */
export type AlignmentBaseline =  'auto'|
'baseline'|
'beforeEdge'|
'textBeforeEdge'|
'middle'|
'central'|
'afterEdge'|
'textAfterEdge'|
'ideographic'|
'alphabetic'|
'hanging'|
'mathematical';

/** `BaselineShift::Number`. */
export interface BaselineShiftNumber {
  /** Discriminant. Narrow on this. */
  type: 'number'
  value: number
}

/** The payload-free variants of `BaselineShift`. */
export interface BaselineShiftPlain {
  /** Discriminant. Narrow on this. */
  type: 'baseline' | 'subscript' | 'superscript'
}

/** A rectangle in SVG user units. */
export interface BBox {
  x: number
  y: number
  width: number
  height: number
}

/** Plain view of a `Blend`. */
export interface Blend {
  input1: InputPlain | InputReference
  input2: InputPlain | InputReference
  mode: BlendMode
}

/**
 * A blending mode property.
 *
 * `mix-blend-mode` attribute in the SVG.
 */
export type BlendMode =  'normal'|
'multiply'|
'screen'|
'overlay'|
'darken'|
'lighten'|
'colorDodge'|
'colorBurn'|
'hardLight'|
'softLight'|
'difference'|
'exclusion'|
'hue'|
'saturation'|
'color'|
'luminosity';

/** Plain view of a `Color`. */
export interface Color {
  red: number
  green: number
  blue: number
}

/** A color channel. */
export type ColorChannel =  'r'|
'g'|
'b'|
'a';

/**
 * A color interpolation mode.
 *
 * The default is `ColorInterpolation::LinearRGB`.
 */
export type ColorInterpolation =  'srgb'|
'linearRgb';

/** Plain view of a `ColorMatrix`. */
export interface ColorMatrix {
  input: InputPlain | InputReference
  kind: ColorMatrixKindPlain | ColorMatrixKindMatrix | ColorMatrixKindSaturate | ColorMatrixKindHueRotate
}

/** `ColorMatrixKind::HueRotate`. */
export interface ColorMatrixKindHueRotate {
  /** Discriminant. Narrow on this. */
  type: 'hueRotate'
  value: number
}

/** `ColorMatrixKind::Matrix`. */
export interface ColorMatrixKindMatrix {
  /** Discriminant. Narrow on this. */
  type: 'matrix'
  value: Array<number>
}

/** The payload-free variants of `ColorMatrixKind`. */
export interface ColorMatrixKindPlain {
  /** Discriminant. Narrow on this. */
  type: 'luminanceToAlpha'
}

/** `ColorMatrixKind::Saturate`. */
export interface ColorMatrixKindSaturate {
  /** Discriminant. Narrow on this. */
  type: 'saturate'
  value: number
}

/** Plain view of a `ComponentTransfer`. */
export interface ComponentTransfer {
  input: InputPlain | InputReference
  funcR: TransferFunctionPlain | TransferFunctionTable | TransferFunctionDiscrete | TransferFunctionLinear | TransferFunctionGamma
  funcG: TransferFunctionPlain | TransferFunctionTable | TransferFunctionDiscrete | TransferFunctionLinear | TransferFunctionGamma
  funcB: TransferFunctionPlain | TransferFunctionTable | TransferFunctionDiscrete | TransferFunctionLinear | TransferFunctionGamma
  funcA: TransferFunctionPlain | TransferFunctionTable | TransferFunctionDiscrete | TransferFunctionLinear | TransferFunctionGamma
}

/** Plain view of a `Composite`. */
export interface Composite {
  input1: InputPlain | InputReference
  input2: InputPlain | InputReference
  operator: CompositeOperatorPlain | CompositeOperatorArithmetic
}

/** `CompositeOperator::Arithmetic`. */
export interface CompositeOperatorArithmetic {
  /** Discriminant. Narrow on this. */
  type: 'arithmetic'
  k1: number
  k2: number
  k3: number
  k4: number
}

/** The payload-free variants of `CompositeOperator`. */
export interface CompositeOperatorPlain {
  /** Discriminant. Narrow on this. */
  type: 'over' | 'in' | 'out' | 'atop' | 'xor'
}

/** Plain view of a `ConvolveMatrix`. */
export interface ConvolveMatrix {
  input: InputPlain | InputReference
  matrix: ConvolveMatrixData
  divisor: number
  bias: number
  edgeMode: EdgeMode
  preserveAlpha: boolean
}

/** Plain view of a `ConvolveMatrixData`. */
export interface ConvolveMatrixData {
  targetX: number
  targetY: number
  columns: number
  rows: number
  data: Array<number>
}

/** Plain view of a `DiffuseLighting`. */
export interface DiffuseLighting {
  input: InputPlain | InputReference
  surfaceScale: number
  diffuseConstant: number
  lightingColor: Color
  lightSource: LightSourceDistantLight | LightSourcePointLight | LightSourceSpotLight
}

/** A width/height pair in SVG user units. */
export interface Dimensions {
  width: number
  height: number
}

/** Plain view of a `DisplacementMap`. */
export interface DisplacementMap {
  input1: InputPlain | InputReference
  input2: InputPlain | InputReference
  scale: number
  xChannelSelector: ColorChannel
  yChannelSelector: ColorChannel
}

/** Plain view of a `DistantLight`. */
export interface DistantLight {
  azimuth: number
  elevation: number
}

/** A dominant baseline property. */
export type DominantBaseline =  'auto'|
'useScript'|
'noChange'|
'resetSize'|
'ideographic'|
'alphabetic'|
'hanging'|
'mathematical'|
'central'|
'middle'|
'textAfterEdge'|
'textBeforeEdge';

/** Plain view of a `DropShadow`. */
export interface DropShadow {
  input: InputPlain | InputReference
  dx: number
  dy: number
  stdDevX: number
  stdDevY: number
  color: Color
  opacity: number
}

/** An edges processing mode. */
export type EdgeMode =  'none'|
'duplicate'|
'wrap';

/** Plain view of a `Fill`. */
export interface Fill {
  paint: PaintColor | PaintLinearGradient | PaintRadialGradient | PaintPattern
  opacity: number
  rule: FillRule
}

/**
 * A fill rule.
 *
 * `fill-rule` attribute in the SVG.
 */
export type FillRule =  'nonZero'|
'evenOdd';

/** Plain view of a `Flood`. */
export interface Flood {
  color: Color
  opacity: number
}

/** Allows italic or oblique faces to be selected. */
export type FontFaceStyle =  'normal'|
'italic'|
'oblique';

/**
 * A font optical sizing property.
 *
 * Controls automatic adjustment of the `opsz` axis in variable fonts
 * based on font size. Matches CSS `font-optical-sizing`.
 */
export type FontOpticalSizing =  'auto'|
'none';

/** A font stretch property. */
export type FontStretch =  'ultraCondensed'|
'extraCondensed'|
'condensed'|
'semiCondensed'|
'normal'|
'semiExpanded'|
'expanded'|
'extraExpanded'|
'ultraExpanded';

/** A font style property. */
export type FontStyle =  'normal'|
'italic'|
'oblique';

/** Plain view of a `FontVariation`. */
export interface FontVariation {
  tag: String
  value: number
}

/** Plain view of a `GaussianBlur`. */
export interface GaussianBlur {
  input: InputPlain | InputReference
  stdDevX: number
  stdDevY: number
}

/** `ImageKind::SVG`. */
export interface ImageKindSvg {
  /** Discriminant. Narrow on this. */
  type: 'svg'
}

/**
 * An image rendering method.
 *
 * `image-rendering` attribute in the SVG.
 */
export type ImageRendering =  'optimizeQuality'|
'optimizeSpeed'|
'smooth'|
'highQuality'|
'crispEdges'|
'pixelated';

/** The payload-free variants of `Input`. */
export interface InputPlain {
  /** Discriminant. Narrow on this. */
  type: 'sourceGraphic' | 'sourceAlpha'
}

/** `Input::Reference`. */
export interface InputReference {
  /** Discriminant. Narrow on this. */
  type: 'reference'
  value: string
}

/** `Kind::Blend`. */
export interface KindBlend {
  /** Discriminant. Narrow on this. */
  type: 'blend'
  value: Blend
}

/** `Kind::ColorMatrix`. */
export interface KindColorMatrix {
  /** Discriminant. Narrow on this. */
  type: 'colorMatrix'
  value: ColorMatrix
}

/** `Kind::ComponentTransfer`. */
export interface KindComponentTransfer {
  /** Discriminant. Narrow on this. */
  type: 'componentTransfer'
  value: ComponentTransfer
}

/** `Kind::Composite`. */
export interface KindComposite {
  /** Discriminant. Narrow on this. */
  type: 'composite'
  value: Composite
}

/** `Kind::ConvolveMatrix`. */
export interface KindConvolveMatrix {
  /** Discriminant. Narrow on this. */
  type: 'convolveMatrix'
  value: ConvolveMatrix
}

/** `Kind::DiffuseLighting`. */
export interface KindDiffuseLighting {
  /** Discriminant. Narrow on this. */
  type: 'diffuseLighting'
  value: DiffuseLighting
}

/** `Kind::DisplacementMap`. */
export interface KindDisplacementMap {
  /** Discriminant. Narrow on this. */
  type: 'displacementMap'
  value: DisplacementMap
}

/** `Kind::DropShadow`. */
export interface KindDropShadow {
  /** Discriminant. Narrow on this. */
  type: 'dropShadow'
  value: DropShadow
}

/** `Kind::Flood`. */
export interface KindFlood {
  /** Discriminant. Narrow on this. */
  type: 'flood'
  value: Flood
}

/** `Kind::GaussianBlur`. */
export interface KindGaussianBlur {
  /** Discriminant. Narrow on this. */
  type: 'gaussianBlur'
  value: GaussianBlur
}

/** `Kind::Image`. */
export interface KindImage {
  /** Discriminant. Narrow on this. */
  type: 'image'
}

/** `Kind::Merge`. */
export interface KindMerge {
  /** Discriminant. Narrow on this. */
  type: 'merge'
  value: Merge
}

/** `Kind::Morphology`. */
export interface KindMorphology {
  /** Discriminant. Narrow on this. */
  type: 'morphology'
  value: Morphology
}

/** `Kind::Offset`. */
export interface KindOffset {
  /** Discriminant. Narrow on this. */
  type: 'offset'
  value: Offset
}

/** `Kind::SpecularLighting`. */
export interface KindSpecularLighting {
  /** Discriminant. Narrow on this. */
  type: 'specularLighting'
  value: SpecularLighting
}

/** `Kind::Tile`. */
export interface KindTile {
  /** Discriminant. Narrow on this. */
  type: 'tile'
  value: Tile
}

/** `Kind::Turbulence`. */
export interface KindTurbulence {
  /** Discriminant. Narrow on this. */
  type: 'turbulence'
  value: Turbulence
}

/** A length adjust property. */
export type LengthAdjust =  'spacing'|
'spacingAndGlyphs';

/** `LightSource::DistantLight`. */
export interface LightSourceDistantLight {
  /** Discriminant. Narrow on this. */
  type: 'distantLight'
  value: DistantLight
}

/** `LightSource::PointLight`. */
export interface LightSourcePointLight {
  /** Discriminant. Narrow on this. */
  type: 'pointLight'
  value: PointLight
}

/** `LightSource::SpotLight`. */
export interface LightSourceSpotLight {
  /** Discriminant. Narrow on this. */
  type: 'spotLight'
  value: SpotLight
}

/**
 * A line cap.
 *
 * `stroke-linecap` attribute in the SVG.
 */
export type LineCap =  'butt'|
'round'|
'square';

/**
 * A line join.
 *
 * `stroke-linejoin` attribute in the SVG.
 */
export type LineJoin =  'miter'|
'miterClip'|
'round'|
'bevel';

/** A mask type. */
export type MaskType =  'luminance'|
'alpha';

/**
 * An affine transform. Field names and order are tiny-skia's.
 *
 * They are *not* the order of SVG's `matrix(a b c d e f)`, which
 * takes `sx ky kx sy tx ty` -- upstream says so itself: "we are
 * using column-major-column-vector matrix notation, therefore it's
 * ky-kx, not kx-ky". Reading these positionally into a `matrix()`
 * string mirrors the transform, silently. Name the fields:
 * `matrix(${m.sx} ${m.ky} ${m.kx} ${m.sy} ${m.tx} ${m.ty})`.
 */
export interface Matrix {
  sx: number
  kx: number
  ky: number
  sy: number
  tx: number
  ty: number
}

/** Plain view of a `Merge`. */
export interface Merge {
  inputs: Array<InputPlain | InputReference>
}

/** Plain view of a `Morphology`. */
export interface Morphology {
  input: InputPlain | InputReference
  operator: MorphologyOperator
  radiusX: number
  radiusY: number
}

/** A morphology operation. */
export type MorphologyOperator =  'erode'|
'dilate';

/** Which flavour of node this is. */
export type NodeKind =  'group'|
'path'|
'image'|
'text';

/** Plain view of a `Offset`. */
export interface Offset {
  input: InputPlain | InputReference
  dx: number
  dy: number
}

/** `Paint::Color`. */
export interface PaintColor {
  /** Discriminant. Narrow on this. */
  type: 'color'
  value: Color
}

/** `Paint::LinearGradient`. */
export interface PaintLinearGradient {
  /** Discriminant. Narrow on this. */
  type: 'linearGradient'
  id: string
}

/**
 * Representation of the [`paint-order`] property.
 *
 * `usvg` will handle `markers` automatically,
 * therefore we provide only `fill` and `stroke` variants.
 *
 * [`paint-order`]: https://www.w3.org/TR/SVG2/painting.html#PaintOrder
 */
export type PaintOrder =  'fillAndStroke'|
'strokeAndFill';

/** `Paint::Pattern`. */
export interface PaintPattern {
  /** Discriminant. Narrow on this. */
  type: 'pattern'
  id: string
}

/** `Paint::RadialGradient`. */
export interface PaintRadialGradient {
  /** Discriminant. Narrow on this. */
  type: 'radialGradient'
  id: string
}

/** Plain view of a `Path`. */
export interface Path {
  id: String
  isVisible: boolean
  fill?: Fill
  stroke?: Stroke
  paintOrder: PaintOrder
  renderingMode: ShapeRendering
  data: Array<PathSegment>
  absTransform: Matrix
  boundingBox: BBox
  absBoundingBox: BBox
  strokeBoundingBox: BBox
  absStrokeBoundingBox: BBox
}

/**
 * One command of a path outline, in the document's own units.
 *
 * `points` holds x,y pairs, and how many depends on `type`: one point
 * for `moveTo` and `lineTo`, two for `quadTo` (control, end), three
 * for `cubicTo` (two controls, end), none for `close`.
 *
 * A flat list rather than a variant per command: a path can carry
 * thousands of segments, and one tagged object each is already the
 * expensive part.
 */
export interface PathSegment {
  type: 'moveTo' | 'lineTo' | 'quadTo' | 'cubicTo' | 'close'
  points: Array<number>
}

/** Plain view of a `PointLight`. */
export interface PointLight {
  x: number
  y: number
  z: number
}

/** Plain view of a `Primitive`. */
export interface Primitive {
  rect: BBox
  colorInterpolation: ColorInterpolation
  result: String
  kind: KindBlend | KindColorMatrix | KindComponentTransfer | KindComposite | KindConvolveMatrix | KindDiffuseLighting | KindDisplacementMap | KindDropShadow | KindFlood | KindGaussianBlur | KindImage | KindMerge | KindMorphology | KindOffset | KindSpecularLighting | KindTile | KindTurbulence
}

/** Un-premultiplied RGBA8 pixels, row-major, no padding. */
export interface RawImage {
  width: number
  height: number
  data: Buffer
}

/**
 * One-shot: parse and render a PNG entirely off the event loop.
 *
 * Uses the process-wide system font database and resolves images off the
 * filesystem only. For a custom `FontDatabase`, supplied image buffers or
 * the `pendingImages` / `pendingFonts` reports, use `Resvg.parseAsync`.
 */
export declare function renderAsync(svg: string | Buffer, options?: RenderOptions | undefined | null, params?: RenderParams | undefined | null, signal?: AbortSignal | undefined | null): Promise<Buffer>

/**
 * Mirror of `usvg::Options`. Every field is optional; omitted fields
 * keep the usvg default.
 */
export interface RenderOptions {
  /**
   * Directory that will be used during relative paths resolving.
   *
   * Expected to be the same as the directory that contains the SVG file,
   * but can be set to any.
   *
   * Default: `None`
   */
  resourcesDir?: string
  /**
   * Target DPI.
   *
   * Impacts units conversion.
   *
   * Default: 96.0
   */
  dpi?: number
  /**
   * A default font family.
   *
   * Will be used when no `font-family` attribute is set in the SVG.
   *
   * Default: Times New Roman
   */
  fontFamily?: string
  /**
   * A default font size.
   *
   * Will be used when no `font-size` attribute is set in the SVG.
   *
   * Default: 12
   */
  fontSize?: number
  /**
   * A list of languages.
   *
   * Will be used to resolve a `systemLanguage` conditional attribute.
   *
   * Format: en, en-US.
   *
   * Default: `[en]`
   */
  languages?: Array<string>
  /**
   * Specifies the default shape rendering method.
   *
   * Will be used when an SVG element's `shape-rendering` property is set to `auto`.
   *
   * Default: GeometricPrecision
   */
  shapeRendering?: ShapeRendering
  /**
   * Specifies the default text rendering method.
   *
   * Will be used when an SVG element's `text-rendering` property is set to `auto`.
   *
   * Default: OptimizeLegibility
   */
  textRendering?: TextRendering
  /**
   * Specifies the default image rendering method.
   *
   * Will be used when an SVG element's `image-rendering` property is set to `auto`.
   *
   * Default: OptimizeQuality
   */
  imageRendering?: ImageRendering
  /**
   * Default viewport size to assume if there is no `viewBox` attribute and
   * the `width` or `height` attributes are relative.
   *
   * Default: `(100, 100)`
   */
  defaultSizeWidth?: number
  /**
   * Default viewport size to assume if there is no `viewBox` attribute and
   * the `width` or `height` attributes are relative.
   *
   * Default: `(100, 100)`
   */
  defaultSizeHeight?: number
  /**
   * A CSS stylesheet that should be injected into the SVG. Can be used to overwrite
   * certain attributes.
   */
  styleSheet?: string
}

/** Output size / scaling of one render pass. */
export interface RenderParams {
  /** Uniform scale factor. Default: 1. */
  scale?: number
  /** Target width in px; keeps the aspect ratio and overrides `scale`. */
  width?: number
  /** Target height in px; keeps the aspect ratio and overrides `scale`. */
  height?: number
  /**
   * Background colour: any CSS3 colour string, e.g. `#eee`, `teal`,
   * `rgba(255, 0, 0, .5)`. Default: transparent.
   */
  background?: string
  /**
   * Render only this rectangle, in SVG user units. `scale` / `width` /
   * `height` then size the crop, not the full viewport. Feed it
   * `absLayerBoundingBox()` to trim the document to its content.
   */
  crop?: BBox
}

/**
 * Starts collecting what usvg and resvg report.
 *
 * `level` is `off`, `error`, `warn`, `info`, `debug` or `trace`. Safe to
 * call repeatedly: the logger is installed once, the level always applies.
 */
export declare function setLogLevel(level: 'off' | 'error' | 'warn' | 'info' | 'debug' | 'trace'): void

/**
 * A shape rendering method.
 *
 * `shape-rendering` attribute in the SVG.
 */
export type ShapeRendering =  'optimizeSpeed'|
'crispEdges'|
'geometricPrecision';

/** Plain view of a `SpecularLighting`. */
export interface SpecularLighting {
  input: InputPlain | InputReference
  surfaceScale: number
  specularConstant: number
  specularExponent: number
  lightingColor: Color
  lightSource: LightSourceDistantLight | LightSourcePointLight | LightSourceSpotLight
}

/** Plain view of a `SpotLight`. */
export interface SpotLight {
  x: number
  y: number
  z: number
  pointsAtX: number
  pointsAtY: number
  pointsAtZ: number
  specularExponent: number
  limitingConeAngle?: number
}

/**
 * A spread method.
 *
 * `spreadMethod` attribute in the SVG.
 */
export type SpreadMethod =  'pad'|
'reflect'|
'repeat';

/** Plain view of a `Stop`. */
export interface Stop {
  offset: number
  color: Color
  opacity: number
}

/** Plain view of a `Stroke`. */
export interface Stroke {
  paint: PaintColor | PaintLinearGradient | PaintRadialGradient | PaintPattern
  dasharray?: Array<number>
  dashoffset: number
  miterlimit: number
  opacity: number
  width: number
  linecap: LineCap
  linejoin: LineJoin
}

/** Drains the messages collected since the last call. */
export declare function takeLogs(): Array<string>

/** A text chunk anchor property. */
export type TextAnchor =  'start'|
'middle'|
'end';

/** Plain view of a `TextDecoration`. */
export interface TextDecoration {
  underline?: TextDecorationStyle
  overline?: TextDecorationStyle
  lineThrough?: TextDecorationStyle
}

/** Plain view of a `TextDecorationStyle`. */
export interface TextDecorationStyle {
  fill?: Fill
  stroke?: Stroke
}

/** `TextFlow::Path`. */
export interface TextFlowPath {
  /** Discriminant. Narrow on this. */
  type: 'path'
  id: string
}

/** The payload-free variants of `TextFlow`. */
export interface TextFlowPlain {
  /** Discriminant. Narrow on this. */
  type: 'linear'
}

/**
 * A text rendering method.
 *
 * `text-rendering` attribute in the SVG.
 */
export type TextRendering =  'optimizeSpeed'|
'optimizeLegibility'|
'geometricPrecision';

/** Plain view of a `Tile`. */
export interface Tile {
  input: InputPlain | InputReference
}

/** `TransferFunction::Discrete`. */
export interface TransferFunctionDiscrete {
  /** Discriminant. Narrow on this. */
  type: 'discrete'
  value: Array<number>
}

/** `TransferFunction::Gamma`. */
export interface TransferFunctionGamma {
  /** Discriminant. Narrow on this. */
  type: 'gamma'
  amplitude: number
  exponent: number
  offset: number
}

/** `TransferFunction::Linear`. */
export interface TransferFunctionLinear {
  /** Discriminant. Narrow on this. */
  type: 'linear'
  slope: number
  intercept: number
}

/** The payload-free variants of `TransferFunction`. */
export interface TransferFunctionPlain {
  /** Discriminant. Narrow on this. */
  type: 'identity'
}

/** `TransferFunction::Table`. */
export interface TransferFunctionTable {
  /** Discriminant. Narrow on this. */
  type: 'table'
  value: Array<number>
}

/** Plain view of a `Turbulence`. */
export interface Turbulence {
  baseFrequencyX: number
  baseFrequencyY: number
  numOctaves: number
  seed: number
  stitchTiles: boolean
  kind: TurbulenceKind
}

/** A turbulence kind for the `feTurbulence` filter. */
export type TurbulenceKind =  'fractalNoise'|
'turbulence';

/**
 * Mirror of `usvg::WriteOptions`, for `Resvg.toString()`. Every field is
 * optional; omitted fields keep the usvg default.
 */
export interface WriteOptions {
  /** Used to add a custom prefix to each element ID during writing. */
  idPrefix?: string
  /**
   * Do not convert text into paths.
   *
   * Default: false
   */
  preserveText?: boolean
  /**
   * Set the coordinates numeric precision.
   *
   * Smaller precision can lead to a malformed output in some cases.
   *
   * Default: 8
   */
  coordinatesPrecision?: number
  /**
   * Set the transform values numeric precision.
   *
   * Smaller precision can lead to a malformed output in some cases.
   *
   * Default: 8
   */
  transformsPrecision?: number
  /**
   * Use single quote marks instead of double quote.
   *
   * # Examples
   *
   * Before:
   *
   * ```text
   * <rect fill="red"/>
   * ```
   *
   * After:
   *
   * ```text
   * <rect fill='red'/>
   * ```
   *
   * Default: disabled
   */
  useSingleQuote?: boolean
}

/** A writing mode. */
export type WritingMode =  'leftToRight'|
'topToBottom';
