// @generated by build.rs from the resvg/usvg/fontdb sources. DO NOT EDIT.
// Regenerate with `touch build.rs && cargo build`.
#![allow(clippy::all, dead_code)]
use napi::bindgen_prelude::*;
use napi_derive::napi;
use resvg::{tiny_skia, usvg};
#[doc = " A color interpolation mode."]
#[doc = ""]
#[doc = " The default is `ColorInterpolation::LinearRGB`."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum ColorInterpolation {
    SRGB,
    LinearRGB,
}
impl From<ColorInterpolation> for usvg::filter::ColorInterpolation {
    fn from(v: ColorInterpolation) -> Self {
        match v {
            ColorInterpolation::SRGB => <usvg::filter::ColorInterpolation>::SRGB,
            ColorInterpolation::LinearRGB => <usvg::filter::ColorInterpolation>::LinearRGB,
        }
    }
}
impl From<usvg::filter::ColorInterpolation> for ColorInterpolation {
    fn from(v: usvg::filter::ColorInterpolation) -> Self {
        match v {
            <usvg::filter::ColorInterpolation>::SRGB => ColorInterpolation::SRGB,
            <usvg::filter::ColorInterpolation>::LinearRGB => ColorInterpolation::LinearRGB,
        }
    }
}
#[doc = " An edges processing mode."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum EdgeMode {
    None,
    Duplicate,
    Wrap,
}
impl From<EdgeMode> for usvg::filter::EdgeMode {
    fn from(v: EdgeMode) -> Self {
        match v {
            EdgeMode::None => <usvg::filter::EdgeMode>::None,
            EdgeMode::Duplicate => <usvg::filter::EdgeMode>::Duplicate,
            EdgeMode::Wrap => <usvg::filter::EdgeMode>::Wrap,
        }
    }
}
impl From<usvg::filter::EdgeMode> for EdgeMode {
    fn from(v: usvg::filter::EdgeMode) -> Self {
        match v {
            <usvg::filter::EdgeMode>::None => EdgeMode::None,
            <usvg::filter::EdgeMode>::Duplicate => EdgeMode::Duplicate,
            <usvg::filter::EdgeMode>::Wrap => EdgeMode::Wrap,
        }
    }
}
#[doc = " A color channel."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum ColorChannel {
    R,
    G,
    B,
    A,
}
impl From<ColorChannel> for usvg::filter::ColorChannel {
    fn from(v: ColorChannel) -> Self {
        match v {
            ColorChannel::R => <usvg::filter::ColorChannel>::R,
            ColorChannel::G => <usvg::filter::ColorChannel>::G,
            ColorChannel::B => <usvg::filter::ColorChannel>::B,
            ColorChannel::A => <usvg::filter::ColorChannel>::A,
        }
    }
}
impl From<usvg::filter::ColorChannel> for ColorChannel {
    fn from(v: usvg::filter::ColorChannel) -> Self {
        match v {
            <usvg::filter::ColorChannel>::R => ColorChannel::R,
            <usvg::filter::ColorChannel>::G => ColorChannel::G,
            <usvg::filter::ColorChannel>::B => ColorChannel::B,
            <usvg::filter::ColorChannel>::A => ColorChannel::A,
        }
    }
}
#[doc = " A morphology operation."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum MorphologyOperator {
    Erode,
    Dilate,
}
impl From<MorphologyOperator> for usvg::filter::MorphologyOperator {
    fn from(v: MorphologyOperator) -> Self {
        match v {
            MorphologyOperator::Erode => <usvg::filter::MorphologyOperator>::Erode,
            MorphologyOperator::Dilate => <usvg::filter::MorphologyOperator>::Dilate,
        }
    }
}
impl From<usvg::filter::MorphologyOperator> for MorphologyOperator {
    fn from(v: usvg::filter::MorphologyOperator) -> Self {
        match v {
            <usvg::filter::MorphologyOperator>::Erode => MorphologyOperator::Erode,
            <usvg::filter::MorphologyOperator>::Dilate => MorphologyOperator::Dilate,
        }
    }
}
#[doc = " A turbulence kind for the `feTurbulence` filter."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum TurbulenceKind {
    FractalNoise,
    Turbulence,
}
impl From<TurbulenceKind> for usvg::filter::TurbulenceKind {
    fn from(v: TurbulenceKind) -> Self {
        match v {
            TurbulenceKind::FractalNoise => <usvg::filter::TurbulenceKind>::FractalNoise,
            TurbulenceKind::Turbulence => <usvg::filter::TurbulenceKind>::Turbulence,
        }
    }
}
impl From<usvg::filter::TurbulenceKind> for TurbulenceKind {
    fn from(v: usvg::filter::TurbulenceKind) -> Self {
        match v {
            <usvg::filter::TurbulenceKind>::FractalNoise => TurbulenceKind::FractalNoise,
            <usvg::filter::TurbulenceKind>::Turbulence => TurbulenceKind::Turbulence,
        }
    }
}
#[doc = " A shape rendering method."]
#[doc = ""]
#[doc = " `shape-rendering` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum ShapeRendering {
    OptimizeSpeed,
    CrispEdges,
    GeometricPrecision,
}
impl From<ShapeRendering> for usvg::ShapeRendering {
    fn from(v: ShapeRendering) -> Self {
        match v {
            ShapeRendering::OptimizeSpeed => <usvg::ShapeRendering>::OptimizeSpeed,
            ShapeRendering::CrispEdges => <usvg::ShapeRendering>::CrispEdges,
            ShapeRendering::GeometricPrecision => <usvg::ShapeRendering>::GeometricPrecision,
        }
    }
}
impl From<usvg::ShapeRendering> for ShapeRendering {
    fn from(v: usvg::ShapeRendering) -> Self {
        match v {
            <usvg::ShapeRendering>::OptimizeSpeed => ShapeRendering::OptimizeSpeed,
            <usvg::ShapeRendering>::CrispEdges => ShapeRendering::CrispEdges,
            <usvg::ShapeRendering>::GeometricPrecision => ShapeRendering::GeometricPrecision,
        }
    }
}
#[doc = " A text rendering method."]
#[doc = ""]
#[doc = " `text-rendering` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum TextRendering {
    OptimizeSpeed,
    OptimizeLegibility,
    GeometricPrecision,
}
impl From<TextRendering> for usvg::TextRendering {
    fn from(v: TextRendering) -> Self {
        match v {
            TextRendering::OptimizeSpeed => <usvg::TextRendering>::OptimizeSpeed,
            TextRendering::OptimizeLegibility => <usvg::TextRendering>::OptimizeLegibility,
            TextRendering::GeometricPrecision => <usvg::TextRendering>::GeometricPrecision,
        }
    }
}
impl From<usvg::TextRendering> for TextRendering {
    fn from(v: usvg::TextRendering) -> Self {
        match v {
            <usvg::TextRendering>::OptimizeSpeed => TextRendering::OptimizeSpeed,
            <usvg::TextRendering>::OptimizeLegibility => TextRendering::OptimizeLegibility,
            <usvg::TextRendering>::GeometricPrecision => TextRendering::GeometricPrecision,
        }
    }
}
#[doc = " An image rendering method."]
#[doc = ""]
#[doc = " `image-rendering` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum ImageRendering {
    OptimizeQuality,
    OptimizeSpeed,
    Smooth,
    HighQuality,
    CrispEdges,
    Pixelated,
}
impl From<ImageRendering> for usvg::ImageRendering {
    fn from(v: ImageRendering) -> Self {
        match v {
            ImageRendering::OptimizeQuality => <usvg::ImageRendering>::OptimizeQuality,
            ImageRendering::OptimizeSpeed => <usvg::ImageRendering>::OptimizeSpeed,
            ImageRendering::Smooth => <usvg::ImageRendering>::Smooth,
            ImageRendering::HighQuality => <usvg::ImageRendering>::HighQuality,
            ImageRendering::CrispEdges => <usvg::ImageRendering>::CrispEdges,
            ImageRendering::Pixelated => <usvg::ImageRendering>::Pixelated,
        }
    }
}
impl From<usvg::ImageRendering> for ImageRendering {
    fn from(v: usvg::ImageRendering) -> Self {
        match v {
            <usvg::ImageRendering>::OptimizeQuality => ImageRendering::OptimizeQuality,
            <usvg::ImageRendering>::OptimizeSpeed => ImageRendering::OptimizeSpeed,
            <usvg::ImageRendering>::Smooth => ImageRendering::Smooth,
            <usvg::ImageRendering>::HighQuality => ImageRendering::HighQuality,
            <usvg::ImageRendering>::CrispEdges => ImageRendering::CrispEdges,
            <usvg::ImageRendering>::Pixelated => ImageRendering::Pixelated,
        }
    }
}
#[doc = " A blending mode property."]
#[doc = ""]
#[doc = " `mix-blend-mode` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum BlendMode {
    Normal,
    Multiply,
    Screen,
    Overlay,
    Darken,
    Lighten,
    ColorDodge,
    ColorBurn,
    HardLight,
    SoftLight,
    Difference,
    Exclusion,
    Hue,
    Saturation,
    Color,
    Luminosity,
}
impl From<BlendMode> for usvg::BlendMode {
    fn from(v: BlendMode) -> Self {
        match v {
            BlendMode::Normal => <usvg::BlendMode>::Normal,
            BlendMode::Multiply => <usvg::BlendMode>::Multiply,
            BlendMode::Screen => <usvg::BlendMode>::Screen,
            BlendMode::Overlay => <usvg::BlendMode>::Overlay,
            BlendMode::Darken => <usvg::BlendMode>::Darken,
            BlendMode::Lighten => <usvg::BlendMode>::Lighten,
            BlendMode::ColorDodge => <usvg::BlendMode>::ColorDodge,
            BlendMode::ColorBurn => <usvg::BlendMode>::ColorBurn,
            BlendMode::HardLight => <usvg::BlendMode>::HardLight,
            BlendMode::SoftLight => <usvg::BlendMode>::SoftLight,
            BlendMode::Difference => <usvg::BlendMode>::Difference,
            BlendMode::Exclusion => <usvg::BlendMode>::Exclusion,
            BlendMode::Hue => <usvg::BlendMode>::Hue,
            BlendMode::Saturation => <usvg::BlendMode>::Saturation,
            BlendMode::Color => <usvg::BlendMode>::Color,
            BlendMode::Luminosity => <usvg::BlendMode>::Luminosity,
        }
    }
}
impl From<usvg::BlendMode> for BlendMode {
    fn from(v: usvg::BlendMode) -> Self {
        match v {
            <usvg::BlendMode>::Normal => BlendMode::Normal,
            <usvg::BlendMode>::Multiply => BlendMode::Multiply,
            <usvg::BlendMode>::Screen => BlendMode::Screen,
            <usvg::BlendMode>::Overlay => BlendMode::Overlay,
            <usvg::BlendMode>::Darken => BlendMode::Darken,
            <usvg::BlendMode>::Lighten => BlendMode::Lighten,
            <usvg::BlendMode>::ColorDodge => BlendMode::ColorDodge,
            <usvg::BlendMode>::ColorBurn => BlendMode::ColorBurn,
            <usvg::BlendMode>::HardLight => BlendMode::HardLight,
            <usvg::BlendMode>::SoftLight => BlendMode::SoftLight,
            <usvg::BlendMode>::Difference => BlendMode::Difference,
            <usvg::BlendMode>::Exclusion => BlendMode::Exclusion,
            <usvg::BlendMode>::Hue => BlendMode::Hue,
            <usvg::BlendMode>::Saturation => BlendMode::Saturation,
            <usvg::BlendMode>::Color => BlendMode::Color,
            <usvg::BlendMode>::Luminosity => BlendMode::Luminosity,
        }
    }
}
#[doc = " A spread method."]
#[doc = ""]
#[doc = " `spreadMethod` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum SpreadMethod {
    Pad,
    Reflect,
    Repeat,
}
impl From<SpreadMethod> for usvg::SpreadMethod {
    fn from(v: SpreadMethod) -> Self {
        match v {
            SpreadMethod::Pad => <usvg::SpreadMethod>::Pad,
            SpreadMethod::Reflect => <usvg::SpreadMethod>::Reflect,
            SpreadMethod::Repeat => <usvg::SpreadMethod>::Repeat,
        }
    }
}
impl From<usvg::SpreadMethod> for SpreadMethod {
    fn from(v: usvg::SpreadMethod) -> Self {
        match v {
            <usvg::SpreadMethod>::Pad => SpreadMethod::Pad,
            <usvg::SpreadMethod>::Reflect => SpreadMethod::Reflect,
            <usvg::SpreadMethod>::Repeat => SpreadMethod::Repeat,
        }
    }
}
#[doc = " A line cap."]
#[doc = ""]
#[doc = " `stroke-linecap` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum LineCap {
    Butt,
    Round,
    Square,
}
impl From<LineCap> for usvg::LineCap {
    fn from(v: LineCap) -> Self {
        match v {
            LineCap::Butt => <usvg::LineCap>::Butt,
            LineCap::Round => <usvg::LineCap>::Round,
            LineCap::Square => <usvg::LineCap>::Square,
        }
    }
}
impl From<usvg::LineCap> for LineCap {
    fn from(v: usvg::LineCap) -> Self {
        match v {
            <usvg::LineCap>::Butt => LineCap::Butt,
            <usvg::LineCap>::Round => LineCap::Round,
            <usvg::LineCap>::Square => LineCap::Square,
        }
    }
}
#[doc = " A line join."]
#[doc = ""]
#[doc = " `stroke-linejoin` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum LineJoin {
    Miter,
    MiterClip,
    Round,
    Bevel,
}
impl From<LineJoin> for usvg::LineJoin {
    fn from(v: LineJoin) -> Self {
        match v {
            LineJoin::Miter => <usvg::LineJoin>::Miter,
            LineJoin::MiterClip => <usvg::LineJoin>::MiterClip,
            LineJoin::Round => <usvg::LineJoin>::Round,
            LineJoin::Bevel => <usvg::LineJoin>::Bevel,
        }
    }
}
impl From<usvg::LineJoin> for LineJoin {
    fn from(v: usvg::LineJoin) -> Self {
        match v {
            <usvg::LineJoin>::Miter => LineJoin::Miter,
            <usvg::LineJoin>::MiterClip => LineJoin::MiterClip,
            <usvg::LineJoin>::Round => LineJoin::Round,
            <usvg::LineJoin>::Bevel => LineJoin::Bevel,
        }
    }
}
#[doc = " A fill rule."]
#[doc = ""]
#[doc = " `fill-rule` attribute in the SVG."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum FillRule {
    NonZero,
    EvenOdd,
}
impl From<FillRule> for usvg::FillRule {
    fn from(v: FillRule) -> Self {
        match v {
            FillRule::NonZero => <usvg::FillRule>::NonZero,
            FillRule::EvenOdd => <usvg::FillRule>::EvenOdd,
        }
    }
}
impl From<usvg::FillRule> for FillRule {
    fn from(v: usvg::FillRule) -> Self {
        match v {
            <usvg::FillRule>::NonZero => FillRule::NonZero,
            <usvg::FillRule>::EvenOdd => FillRule::EvenOdd,
        }
    }
}
#[doc = " A mask type."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum MaskType {
    Luminance,
    Alpha,
}
impl From<MaskType> for usvg::MaskType {
    fn from(v: MaskType) -> Self {
        match v {
            MaskType::Luminance => <usvg::MaskType>::Luminance,
            MaskType::Alpha => <usvg::MaskType>::Alpha,
        }
    }
}
impl From<usvg::MaskType> for MaskType {
    fn from(v: usvg::MaskType) -> Self {
        match v {
            <usvg::MaskType>::Luminance => MaskType::Luminance,
            <usvg::MaskType>::Alpha => MaskType::Alpha,
        }
    }
}
#[doc = " Representation of the [`paint-order`] property."]
#[doc = ""]
#[doc = " `usvg` will handle `markers` automatically,"]
#[doc = " therefore we provide only `fill` and `stroke` variants."]
#[doc = ""]
#[doc = " [`paint-order`]: https://www.w3.org/TR/SVG2/painting.html#PaintOrder"]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum PaintOrder {
    FillAndStroke,
    StrokeAndFill,
}
impl From<PaintOrder> for usvg::PaintOrder {
    fn from(v: PaintOrder) -> Self {
        match v {
            PaintOrder::FillAndStroke => <usvg::PaintOrder>::FillAndStroke,
            PaintOrder::StrokeAndFill => <usvg::PaintOrder>::StrokeAndFill,
        }
    }
}
impl From<usvg::PaintOrder> for PaintOrder {
    fn from(v: usvg::PaintOrder) -> Self {
        match v {
            <usvg::PaintOrder>::FillAndStroke => PaintOrder::FillAndStroke,
            <usvg::PaintOrder>::StrokeAndFill => PaintOrder::StrokeAndFill,
        }
    }
}
#[doc = " A font stretch property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum FontStretch {
    UltraCondensed,
    ExtraCondensed,
    Condensed,
    SemiCondensed,
    Normal,
    SemiExpanded,
    Expanded,
    ExtraExpanded,
    UltraExpanded,
}
impl From<FontStretch> for usvg::FontStretch {
    fn from(v: FontStretch) -> Self {
        match v {
            FontStretch::UltraCondensed => <usvg::FontStretch>::UltraCondensed,
            FontStretch::ExtraCondensed => <usvg::FontStretch>::ExtraCondensed,
            FontStretch::Condensed => <usvg::FontStretch>::Condensed,
            FontStretch::SemiCondensed => <usvg::FontStretch>::SemiCondensed,
            FontStretch::Normal => <usvg::FontStretch>::Normal,
            FontStretch::SemiExpanded => <usvg::FontStretch>::SemiExpanded,
            FontStretch::Expanded => <usvg::FontStretch>::Expanded,
            FontStretch::ExtraExpanded => <usvg::FontStretch>::ExtraExpanded,
            FontStretch::UltraExpanded => <usvg::FontStretch>::UltraExpanded,
        }
    }
}
impl From<usvg::FontStretch> for FontStretch {
    fn from(v: usvg::FontStretch) -> Self {
        match v {
            <usvg::FontStretch>::UltraCondensed => FontStretch::UltraCondensed,
            <usvg::FontStretch>::ExtraCondensed => FontStretch::ExtraCondensed,
            <usvg::FontStretch>::Condensed => FontStretch::Condensed,
            <usvg::FontStretch>::SemiCondensed => FontStretch::SemiCondensed,
            <usvg::FontStretch>::Normal => FontStretch::Normal,
            <usvg::FontStretch>::SemiExpanded => FontStretch::SemiExpanded,
            <usvg::FontStretch>::Expanded => FontStretch::Expanded,
            <usvg::FontStretch>::ExtraExpanded => FontStretch::ExtraExpanded,
            <usvg::FontStretch>::UltraExpanded => FontStretch::UltraExpanded,
        }
    }
}
#[doc = " A font style property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum FontStyle {
    Normal,
    Italic,
    Oblique,
}
impl From<FontStyle> for usvg::FontStyle {
    fn from(v: FontStyle) -> Self {
        match v {
            FontStyle::Normal => <usvg::FontStyle>::Normal,
            FontStyle::Italic => <usvg::FontStyle>::Italic,
            FontStyle::Oblique => <usvg::FontStyle>::Oblique,
        }
    }
}
impl From<usvg::FontStyle> for FontStyle {
    fn from(v: usvg::FontStyle) -> Self {
        match v {
            <usvg::FontStyle>::Normal => FontStyle::Normal,
            <usvg::FontStyle>::Italic => FontStyle::Italic,
            <usvg::FontStyle>::Oblique => FontStyle::Oblique,
        }
    }
}
#[doc = " A dominant baseline property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum DominantBaseline {
    Auto,
    UseScript,
    NoChange,
    ResetSize,
    Ideographic,
    Alphabetic,
    Hanging,
    Mathematical,
    Central,
    Middle,
    TextAfterEdge,
    TextBeforeEdge,
}
impl From<DominantBaseline> for usvg::DominantBaseline {
    fn from(v: DominantBaseline) -> Self {
        match v {
            DominantBaseline::Auto => <usvg::DominantBaseline>::Auto,
            DominantBaseline::UseScript => <usvg::DominantBaseline>::UseScript,
            DominantBaseline::NoChange => <usvg::DominantBaseline>::NoChange,
            DominantBaseline::ResetSize => <usvg::DominantBaseline>::ResetSize,
            DominantBaseline::Ideographic => <usvg::DominantBaseline>::Ideographic,
            DominantBaseline::Alphabetic => <usvg::DominantBaseline>::Alphabetic,
            DominantBaseline::Hanging => <usvg::DominantBaseline>::Hanging,
            DominantBaseline::Mathematical => <usvg::DominantBaseline>::Mathematical,
            DominantBaseline::Central => <usvg::DominantBaseline>::Central,
            DominantBaseline::Middle => <usvg::DominantBaseline>::Middle,
            DominantBaseline::TextAfterEdge => <usvg::DominantBaseline>::TextAfterEdge,
            DominantBaseline::TextBeforeEdge => <usvg::DominantBaseline>::TextBeforeEdge,
        }
    }
}
impl From<usvg::DominantBaseline> for DominantBaseline {
    fn from(v: usvg::DominantBaseline) -> Self {
        match v {
            <usvg::DominantBaseline>::Auto => DominantBaseline::Auto,
            <usvg::DominantBaseline>::UseScript => DominantBaseline::UseScript,
            <usvg::DominantBaseline>::NoChange => DominantBaseline::NoChange,
            <usvg::DominantBaseline>::ResetSize => DominantBaseline::ResetSize,
            <usvg::DominantBaseline>::Ideographic => DominantBaseline::Ideographic,
            <usvg::DominantBaseline>::Alphabetic => DominantBaseline::Alphabetic,
            <usvg::DominantBaseline>::Hanging => DominantBaseline::Hanging,
            <usvg::DominantBaseline>::Mathematical => DominantBaseline::Mathematical,
            <usvg::DominantBaseline>::Central => DominantBaseline::Central,
            <usvg::DominantBaseline>::Middle => DominantBaseline::Middle,
            <usvg::DominantBaseline>::TextAfterEdge => DominantBaseline::TextAfterEdge,
            <usvg::DominantBaseline>::TextBeforeEdge => DominantBaseline::TextBeforeEdge,
        }
    }
}
#[doc = " An alignment baseline property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum AlignmentBaseline {
    Auto,
    Baseline,
    BeforeEdge,
    TextBeforeEdge,
    Middle,
    Central,
    AfterEdge,
    TextAfterEdge,
    Ideographic,
    Alphabetic,
    Hanging,
    Mathematical,
}
impl From<AlignmentBaseline> for usvg::AlignmentBaseline {
    fn from(v: AlignmentBaseline) -> Self {
        match v {
            AlignmentBaseline::Auto => <usvg::AlignmentBaseline>::Auto,
            AlignmentBaseline::Baseline => <usvg::AlignmentBaseline>::Baseline,
            AlignmentBaseline::BeforeEdge => <usvg::AlignmentBaseline>::BeforeEdge,
            AlignmentBaseline::TextBeforeEdge => <usvg::AlignmentBaseline>::TextBeforeEdge,
            AlignmentBaseline::Middle => <usvg::AlignmentBaseline>::Middle,
            AlignmentBaseline::Central => <usvg::AlignmentBaseline>::Central,
            AlignmentBaseline::AfterEdge => <usvg::AlignmentBaseline>::AfterEdge,
            AlignmentBaseline::TextAfterEdge => <usvg::AlignmentBaseline>::TextAfterEdge,
            AlignmentBaseline::Ideographic => <usvg::AlignmentBaseline>::Ideographic,
            AlignmentBaseline::Alphabetic => <usvg::AlignmentBaseline>::Alphabetic,
            AlignmentBaseline::Hanging => <usvg::AlignmentBaseline>::Hanging,
            AlignmentBaseline::Mathematical => <usvg::AlignmentBaseline>::Mathematical,
        }
    }
}
impl From<usvg::AlignmentBaseline> for AlignmentBaseline {
    fn from(v: usvg::AlignmentBaseline) -> Self {
        match v {
            <usvg::AlignmentBaseline>::Auto => AlignmentBaseline::Auto,
            <usvg::AlignmentBaseline>::Baseline => AlignmentBaseline::Baseline,
            <usvg::AlignmentBaseline>::BeforeEdge => AlignmentBaseline::BeforeEdge,
            <usvg::AlignmentBaseline>::TextBeforeEdge => AlignmentBaseline::TextBeforeEdge,
            <usvg::AlignmentBaseline>::Middle => AlignmentBaseline::Middle,
            <usvg::AlignmentBaseline>::Central => AlignmentBaseline::Central,
            <usvg::AlignmentBaseline>::AfterEdge => AlignmentBaseline::AfterEdge,
            <usvg::AlignmentBaseline>::TextAfterEdge => AlignmentBaseline::TextAfterEdge,
            <usvg::AlignmentBaseline>::Ideographic => AlignmentBaseline::Ideographic,
            <usvg::AlignmentBaseline>::Alphabetic => AlignmentBaseline::Alphabetic,
            <usvg::AlignmentBaseline>::Hanging => AlignmentBaseline::Hanging,
            <usvg::AlignmentBaseline>::Mathematical => AlignmentBaseline::Mathematical,
        }
    }
}
#[doc = " A length adjust property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum LengthAdjust {
    Spacing,
    SpacingAndGlyphs,
}
impl From<LengthAdjust> for usvg::LengthAdjust {
    fn from(v: LengthAdjust) -> Self {
        match v {
            LengthAdjust::Spacing => <usvg::LengthAdjust>::Spacing,
            LengthAdjust::SpacingAndGlyphs => <usvg::LengthAdjust>::SpacingAndGlyphs,
        }
    }
}
impl From<usvg::LengthAdjust> for LengthAdjust {
    fn from(v: usvg::LengthAdjust) -> Self {
        match v {
            <usvg::LengthAdjust>::Spacing => LengthAdjust::Spacing,
            <usvg::LengthAdjust>::SpacingAndGlyphs => LengthAdjust::SpacingAndGlyphs,
        }
    }
}
#[doc = " A font optical sizing property."]
#[doc = ""]
#[doc = " Controls automatic adjustment of the `opsz` axis in variable fonts"]
#[doc = " based on font size. Matches CSS `font-optical-sizing`."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum FontOpticalSizing {
    Auto,
    None,
}
impl From<FontOpticalSizing> for usvg::FontOpticalSizing {
    fn from(v: FontOpticalSizing) -> Self {
        match v {
            FontOpticalSizing::Auto => <usvg::FontOpticalSizing>::Auto,
            FontOpticalSizing::None => <usvg::FontOpticalSizing>::None,
        }
    }
}
impl From<usvg::FontOpticalSizing> for FontOpticalSizing {
    fn from(v: usvg::FontOpticalSizing) -> Self {
        match v {
            <usvg::FontOpticalSizing>::Auto => FontOpticalSizing::Auto,
            <usvg::FontOpticalSizing>::None => FontOpticalSizing::None,
        }
    }
}
#[doc = " A text chunk anchor property."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum TextAnchor {
    Start,
    Middle,
    End,
}
impl From<TextAnchor> for usvg::TextAnchor {
    fn from(v: TextAnchor) -> Self {
        match v {
            TextAnchor::Start => <usvg::TextAnchor>::Start,
            TextAnchor::Middle => <usvg::TextAnchor>::Middle,
            TextAnchor::End => <usvg::TextAnchor>::End,
        }
    }
}
impl From<usvg::TextAnchor> for TextAnchor {
    fn from(v: usvg::TextAnchor) -> Self {
        match v {
            <usvg::TextAnchor>::Start => TextAnchor::Start,
            <usvg::TextAnchor>::Middle => TextAnchor::Middle,
            <usvg::TextAnchor>::End => TextAnchor::End,
        }
    }
}
#[doc = " A writing mode."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum WritingMode {
    LeftToRight,
    TopToBottom,
}
impl From<WritingMode> for usvg::WritingMode {
    fn from(v: WritingMode) -> Self {
        match v {
            WritingMode::LeftToRight => <usvg::WritingMode>::LeftToRight,
            WritingMode::TopToBottom => <usvg::WritingMode>::TopToBottom,
        }
    }
}
impl From<usvg::WritingMode> for WritingMode {
    fn from(v: usvg::WritingMode) -> Self {
        match v {
            <usvg::WritingMode>::LeftToRight => WritingMode::LeftToRight,
            <usvg::WritingMode>::TopToBottom => WritingMode::TopToBottom,
        }
    }
}
#[doc = " Mirror of `usvg::Options`. Every field is optional; omitted fields"]
#[doc = " keep the usvg default."]
#[napi(object)]
#[derive(Default, Clone)]
pub struct RenderOptions {
    #[doc = " Directory that will be used during relative paths resolving."]
    #[doc = ""]
    #[doc = " Expected to be the same as the directory that contains the SVG file,"]
    #[doc = " but can be set to any."]
    #[doc = ""]
    #[doc = " Default: `None`"]
    pub resources_dir: Option<String>,
    #[doc = " Target DPI."]
    #[doc = ""]
    #[doc = " Impacts units conversion."]
    #[doc = ""]
    #[doc = " Default: 96.0"]
    pub dpi: Option<f64>,
    #[doc = " A default font family."]
    #[doc = ""]
    #[doc = " Will be used when no `font-family` attribute is set in the SVG."]
    #[doc = ""]
    #[doc = " Default: Times New Roman"]
    pub font_family: Option<String>,
    #[doc = " A default font size."]
    #[doc = ""]
    #[doc = " Will be used when no `font-size` attribute is set in the SVG."]
    #[doc = ""]
    #[doc = " Default: 12"]
    pub font_size: Option<f64>,
    #[doc = " A list of languages."]
    #[doc = ""]
    #[doc = " Will be used to resolve a `systemLanguage` conditional attribute."]
    #[doc = ""]
    #[doc = " Format: en, en-US."]
    #[doc = ""]
    #[doc = " Default: `[en]`"]
    pub languages: Option<Vec<String>>,
    #[doc = " Specifies the default shape rendering method."]
    #[doc = ""]
    #[doc = " Will be used when an SVG element's `shape-rendering` property is set to `auto`."]
    #[doc = ""]
    #[doc = " Default: GeometricPrecision"]
    pub shape_rendering: Option<ShapeRendering>,
    #[doc = " Specifies the default text rendering method."]
    #[doc = ""]
    #[doc = " Will be used when an SVG element's `text-rendering` property is set to `auto`."]
    #[doc = ""]
    #[doc = " Default: OptimizeLegibility"]
    pub text_rendering: Option<TextRendering>,
    #[doc = " Specifies the default image rendering method."]
    #[doc = ""]
    #[doc = " Will be used when an SVG element's `image-rendering` property is set to `auto`."]
    #[doc = ""]
    #[doc = " Default: OptimizeQuality"]
    pub image_rendering: Option<ImageRendering>,
    #[doc = " Default viewport size to assume if there is no `viewBox` attribute and"]
    #[doc = " the `width` or `height` attributes are relative."]
    #[doc = ""]
    #[doc = " Default: `(100, 100)`"]
    pub default_size_width: Option<f64>,
    #[doc = " Default viewport size to assume if there is no `viewBox` attribute and"]
    #[doc = " the `width` or `height` attributes are relative."]
    #[doc = ""]
    #[doc = " Default: `(100, 100)`"]
    pub default_size_height: Option<f64>,
    #[doc = " A CSS stylesheet that should be injected into the SVG. Can be used to overwrite"]
    #[doc = " certain attributes."]
    pub style_sheet: Option<String>,
}
#[doc = " System fonts are expensive to enumerate, so do it once per process."]
fn default_fontdb() -> std::sync::Arc<usvg::fontdb::Database> {
    static DB: std::sync::OnceLock<std::sync::Arc<usvg::fontdb::Database>> =
        std::sync::OnceLock::new();
    DB.get_or_init(|| {
        let mut db = usvg::fontdb::Database::new();
        db.load_system_fonts();
        std::sync::Arc::new(db)
    })
    .clone()
}
impl RenderOptions {
    fn to_usvg(&self, fonts: std::sync::Arc<usvg::fontdb::Database>) -> usvg::Options<'static> {
        let mut o = usvg::Options::default();
        o.resources_dir = self.resources_dir.as_deref().map(std::path::PathBuf::from);
        if let Some(v) = self.dpi {
            o.dpi = v as f32;
        }
        if let Some(v) = &self.font_family {
            o.font_family = v.clone();
        }
        if let Some(v) = self.font_size {
            o.font_size = v as f32;
        }
        if let Some(v) = &self.languages {
            o.languages = v.clone();
        }
        if let Some(v) = self.shape_rendering {
            o.shape_rendering = v.into();
        }
        if let Some(v) = self.text_rendering {
            o.text_rendering = v.into();
        }
        if let Some(v) = self.image_rendering {
            o.image_rendering = v.into();
        }
        if let (Some(w), Some(h)) = (self.default_size_width, self.default_size_height) {
            if let Some(s) = usvg::Size::from_wh(w as f32, h as f32) {
                o.default_size = s;
            }
        }
        o.style_sheet = self.style_sheet.clone();
        o.fontdb = fonts;
        o
    }
}
type ImageMap = std::collections::HashMap<String, std::sync::Arc<Vec<u8>>>;
#[doc = " Hrefs no resolver could satisfy during the last parse."]
#[derive(Default, Clone)]
struct Misses(std::sync::Arc<std::sync::Mutex<Vec<String>>>);
#[doc = " `usvg::ImageHrefResolver` demands `Send + Sync`, so a JS callback cannot"]
#[doc = " live in it. Buffers are handed over up front instead, and whatever stays"]
#[doc = " unresolved is reported back to JS for a second pass."]
fn href_resolver(images: ImageMap, misses: Misses) -> usvg::ImageHrefResolver<'static> {
    let from_disk = usvg::ImageHrefResolver::default_string_resolver();
    let sniff = usvg::ImageHrefResolver::default_data_resolver();
    usvg::ImageHrefResolver {
        resolve_data: usvg::ImageHrefResolver::default_data_resolver(),
        resolve_string: Box::new(move |href: &str, opts: &usvg::Options| {
            if let Some(data) = images.get(href) {
                return sniff("text/plain", data.clone(), opts);
            }
            if let Some(kind) = from_disk(href, opts) {
                return Some(kind);
            }
            misses.0.lock().unwrap().push(href.to_string());
            None
        }),
    }
}
#[doc = " Opaque wrapper over `fontdb::Database` (memory-mapped faces, no JSON form)."]
#[napi]
pub struct FontDatabase {
    inner: usvg::fontdb::Database,
}
impl FontDatabase {
    #[doc = " Snapshot of a shared database, e.g. the one a parse resolved."]
    fn wrap(inner: std::sync::Arc<usvg::fontdb::Database>) -> Self {
        Self {
            inner: (*inner).clone(),
        }
    }
}
#[napi]
impl FontDatabase {
    #[doc = " Which face this database would pick for a CSS font request."]
    #[doc = ""]
    #[doc = " Decision, not a derivation: `fontdb::Query` borrows a `&[Family]`"]
    #[doc = " whose `Name` variant holds a `&str`, so it cannot be rebuilt from a"]
    #[doc = " JS object. The request is taken apart into plain arguments instead;"]
    #[doc = " `serif`, `sans-serif`, `cursive`, `fantasy` and `monospace` are"]
    #[doc = " understood as the generic families."]
    #[napi]
    pub fn query(
        &self,
        families: Vec<String>,
        weight: Option<u32>,
        italic: Option<bool>,
    ) -> Option<FontFace> {
        let names: Vec<usvg::fontdb::Family> = families
            .iter()
            .map(|f| match f.as_str() {
                "serif" => usvg::fontdb::Family::Serif,
                "sans-serif" => usvg::fontdb::Family::SansSerif,
                "cursive" => usvg::fontdb::Family::Cursive,
                "fantasy" => usvg::fontdb::Family::Fantasy,
                "monospace" => usvg::fontdb::Family::Monospace,
                other => usvg::fontdb::Family::Name(other),
            })
            .collect();
        let query = usvg::fontdb::Query {
            families: &names,
            weight: usvg::fontdb::Weight(weight.unwrap_or(400) as u16),
            style: if italic.unwrap_or(false) {
                usvg::fontdb::Style::Italic
            } else {
                usvg::fontdb::Style::Normal
            },
            ..Default::default()
        };
        let id = self.inner.query(&query)?;
        self.inner.face(id).cloned().map(FontFace::wrap)
    }
    #[doc = " Raw bytes of a face, by PostScript name (see `faces()`)."]
    #[doc = ""]
    #[doc = " Decision, not a derivation: upstream exposes this through"]
    #[doc = " `with_face_data<P: FnOnce(&[u8], u32) -> T>` plus an opaque `ID`."]
    #[doc = " Neither a closure nor that key crosses to JS, so the lookup key is"]
    #[doc = " the PostScript name and the bytes are copied out."]
    #[napi]
    pub fn face_data(&self, post_script_name: String) -> Option<Buffer> {
        let id = self
            .inner
            .faces()
            .find(|f| f.post_script_name == post_script_name)
            .map(|f| f.id)?;
        self.inner
            .with_face_data(id, |data, _index| Buffer::from(data.to_vec()))
    }
    #[napi(constructor)]
    pub fn new() -> Self {
        Self {
            inner: usvg::fontdb::Database::new(),
        }
    }
    #[doc = " Loads a font data into the `Database`."]
    #[doc = ""]
    #[doc = " Will load all font faces in case of a font collection."]
    #[napi]
    pub fn load_font_data(&mut self, data: Buffer) -> () {
        self.inner.load_font_data(data.to_vec())
    }
    #[doc = " Loads a font file into the `Database`."]
    #[doc = ""]
    #[doc = " Will load all font faces in case of a font collection."]
    #[napi]
    pub fn load_font_file(&mut self, path: String) -> Result<()> {
        Ok(self
            .inner
            .load_font_file(path)
            .map_err(|e| Error::from_reason(e.to_string()))?)
    }
    #[doc = " Loads font files from the selected directory into the `Database`."]
    #[doc = ""]
    #[doc = " This method will scan directories recursively."]
    #[doc = ""]
    #[doc = " Will load `ttf`, `otf`, `ttc` and `otc` fonts."]
    #[doc = ""]
    #[doc = " Unlike other `load_*` methods, this one doesn't return an error."]
    #[doc = " It will simply skip malformed fonts and will print a warning into the log for each of them."]
    #[napi]
    pub fn load_fonts_dir(&mut self, dir: String) -> () {
        self.inner.load_fonts_dir(dir)
    }
    #[doc = " Attempts to load system fonts."]
    #[doc = ""]
    #[doc = " Supports Windows, Linux and macOS."]
    #[doc = ""]
    #[doc = " System fonts loading is a surprisingly complicated task,"]
    #[doc = " mostly unsolvable without interacting with system libraries."]
    #[doc = " And since `fontdb` tries to be small and portable, this method"]
    #[doc = " will simply scan some predefined directories."]
    #[doc = " Which means that fonts that are not in those directories must"]
    #[doc = " be added manually."]
    #[napi]
    pub fn load_system_fonts(&mut self) -> () {
        self.inner.load_system_fonts()
    }
    #[doc = " Removes a font face by `id` from the database."]
    #[doc = ""]
    #[doc = " Returns `false` while attempting to remove a non-existing font face."]
    #[doc = ""]
    #[doc = " Useful when you want to ignore some specific font face(s)"]
    #[doc = " after loading a large directory with fonts."]
    #[doc = " Or a specific face from a font."]
    #[napi]
    pub fn remove_face(&mut self, id: &FontFace) -> () {
        self.inner.remove_face(id.inner.id)
    }
    #[doc = " Returns `true` if the `Database` contains no font faces."]
    #[napi]
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
    #[doc = " Returns the number of font faces in the `Database`."]
    #[doc = ""]
    #[doc = " Note that `Database` stores font faces, not fonts."]
    #[doc = " For example, if a caller will try to load a font collection (`*.ttc`) that contains 5 faces,"]
    #[doc = " then the `Database` will load 5 font faces and this method will return 5, not 1."]
    #[napi]
    pub fn len(&self) -> u32 {
        self.inner.len() as u32
    }
    #[doc = " Sets the family that will be used by `Family::Serif`."]
    #[napi]
    pub fn set_serif_family(&mut self, family: String) -> () {
        self.inner.set_serif_family(family)
    }
    #[doc = " Sets the family that will be used by `Family::SansSerif`."]
    #[napi]
    pub fn set_sans_serif_family(&mut self, family: String) -> () {
        self.inner.set_sans_serif_family(family)
    }
    #[doc = " Sets the family that will be used by `Family::Cursive`."]
    #[napi]
    pub fn set_cursive_family(&mut self, family: String) -> () {
        self.inner.set_cursive_family(family)
    }
    #[doc = " Sets the family that will be used by `Family::Fantasy`."]
    #[napi]
    pub fn set_fantasy_family(&mut self, family: String) -> () {
        self.inner.set_fantasy_family(family)
    }
    #[doc = " Sets the family that will be used by `Family::Monospace`."]
    #[napi]
    pub fn set_monospace_family(&mut self, family: String) -> () {
        self.inner.set_monospace_family(family)
    }
    #[doc = " Returns an iterator over the internal storage."]
    #[doc = ""]
    #[doc = " This can be used for manual font matching."]
    #[napi]
    pub fn faces(&self) -> Vec<FontFace> {
        self.inner
            .faces()
            .into_iter()
            .map(|x| FontFace::wrap(x.clone()))
            .collect()
    }
    #[doc = " Selects a `FaceInfo` by `id`."]
    #[doc = ""]
    #[doc = " Returns `None` if a face with such ID was already removed,"]
    #[doc = " or this ID belong to the other `Database`."]
    #[napi]
    pub fn face(&self, id: &FontFace) -> Option<FontFace> {
        self.inner
            .face(id.inner.id)
            .map(|x| FontFace::wrap(x.clone()))
    }
    #[doc = " Transfers ownership of shared font data back to the font database. This is the reverse operation"]
    #[doc = " of [`Self::make_shared_face_data`]. If the font data belonging to the specified face is mapped"]
    #[doc = " from a file on disk, then that mapping is closed and the data becomes private to the process again."]
    #[napi]
    pub fn make_face_data_unshared(&mut self, id: &FontFace) -> () {
        self.inner.make_face_data_unshared(id.inner.id)
    }
}
#[doc = " Mirror of `usvg::WriteOptions`, for `Resvg.toString()`. Every field is"]
#[doc = " optional; omitted fields keep the usvg default."]
#[napi(object)]
#[derive(Default, Clone)]
pub struct WriteOptions {
    #[doc = " Used to add a custom prefix to each element ID during writing."]
    pub id_prefix: Option<String>,
    #[doc = " Do not convert text into paths."]
    #[doc = ""]
    #[doc = " Default: false"]
    pub preserve_text: Option<bool>,
    #[doc = " Set the coordinates numeric precision."]
    #[doc = ""]
    #[doc = " Smaller precision can lead to a malformed output in some cases."]
    #[doc = ""]
    #[doc = " Default: 8"]
    pub coordinates_precision: Option<u32>,
    #[doc = " Set the transform values numeric precision."]
    #[doc = ""]
    #[doc = " Smaller precision can lead to a malformed output in some cases."]
    #[doc = ""]
    #[doc = " Default: 8"]
    pub transforms_precision: Option<u32>,
    #[doc = " Use single quote marks instead of double quote."]
    #[doc = ""]
    #[doc = " # Examples"]
    #[doc = ""]
    #[doc = " Before:"]
    #[doc = ""]
    #[doc = " ```text"]
    #[doc = " <rect fill=\"red\"/>"]
    #[doc = " ```"]
    #[doc = ""]
    #[doc = " After:"]
    #[doc = ""]
    #[doc = " ```text"]
    #[doc = " <rect fill='red'/>"]
    #[doc = " ```"]
    #[doc = ""]
    #[doc = " Default: disabled"]
    pub use_single_quote: Option<bool>,
}
impl WriteOptions {
    fn to_usvg(&self) -> usvg::WriteOptions {
        let mut o = usvg::WriteOptions::default();
        o.id_prefix = self.id_prefix.clone();
        if let Some(v) = self.preserve_text {
            o.preserve_text = v;
        }
        if let Some(v) = self.coordinates_precision {
            o.coordinates_precision = v.min(12u32) as u8;
        }
        if let Some(v) = self.transforms_precision {
            o.transforms_precision = v.min(12u32) as u8;
        }
        if let Some(v) = self.use_single_quote {
            o.use_single_quote = v;
        }
        o
    }
}
#[doc = " Output size / scaling of one render pass."]
#[napi(object)]
#[derive(Default, Clone)]
pub struct RenderParams {
    #[doc = " Uniform scale factor. Default: 1."]
    pub scale: Option<f64>,
    #[doc = " Target width in px; keeps the aspect ratio and overrides `scale`."]
    pub width: Option<u32>,
    #[doc = " Target height in px; keeps the aspect ratio and overrides `scale`."]
    pub height: Option<u32>,
    #[doc = " Background colour: any CSS3 colour string, e.g. `#eee`, `teal`,"]
    #[doc = " `rgba(255, 0, 0, .5)`. Default: transparent."]
    pub background: Option<String>,
    #[doc = " Render only this rectangle, in SVG user units. `scale` / `width` /"]
    #[doc = " `height` then size the crop, not the full viewport. Feed it"]
    #[doc = " `absLayerBoundingBox()` to trim the document to its content."]
    pub crop: Option<BBox>,
}
#[doc = " An affine transform, same field order as SVG's `matrix(...)`."]
#[napi(object)]
#[derive(Clone, Copy)]
pub struct Matrix {
    pub sx: f64,
    pub kx: f64,
    pub ky: f64,
    pub sy: f64,
    pub tx: f64,
    pub ty: f64,
}
impl From<usvg::Transform> for Matrix {
    fn from(t: usvg::Transform) -> Self {
        Self {
            sx: t.sx as f64,
            kx: t.kx as f64,
            ky: t.ky as f64,
            sy: t.sy as f64,
            tx: t.tx as f64,
            ty: t.ty as f64,
        }
    }
}
#[doc = " A width/height pair in SVG user units."]
#[napi(object)]
#[derive(Clone, Copy)]
pub struct Dimensions {
    pub width: f64,
    pub height: f64,
}
impl From<usvg::Size> for Dimensions {
    fn from(s: usvg::Size) -> Self {
        Self {
            width: s.width() as f64,
            height: s.height() as f64,
        }
    }
}
#[doc = " A rectangle in SVG user units."]
#[napi(object)]
#[derive(Clone, Copy)]
pub struct BBox {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}
impl From<usvg::Rect> for BBox {
    fn from(r: usvg::Rect) -> Self {
        Self {
            x: r.x() as f64,
            y: r.y() as f64,
            width: r.width() as f64,
            height: r.height() as f64,
        }
    }
}
impl From<usvg::NonZeroRect> for BBox {
    fn from(r: usvg::NonZeroRect) -> Self {
        Self {
            x: r.x() as f64,
            y: r.y() as f64,
            width: r.width() as f64,
            height: r.height() as f64,
        }
    }
}
#[doc = " Un-premultiplied RGBA8 pixels, row-major, no padding."]
#[napi(object)]
pub struct RawImage {
    pub width: u32,
    pub height: u32,
    pub data: Buffer,
}
#[doc = " Same trick for fonts: the resolver is `Send + Sync` too, so instead of"]
#[doc = " calling into JS we wrap the default selector and note every named family"]
#[doc = " the database does not carry -- i.e. text that silently fell back."]
fn font_resolver(misses: Misses) -> usvg::FontResolver<'static> {
    let select = usvg::FontResolver::default_font_selector();
    usvg::FontResolver {
        select_font: Box::new(
            move |font: &usvg::Font, db: &mut std::sync::Arc<usvg::fontdb::Database>| {
                for family in font.families() {
                    let usvg::FontFamily::Named(name) = family else {
                        continue;
                    };
                    let known = db
                        .faces()
                        .any(|f| f.families.iter().any(|(n, _)| n.eq_ignore_ascii_case(name)));
                    if !known {
                        let mut seen = misses.0.lock().unwrap();
                        if !seen.iter().any(|s| s == name) {
                            seen.push(name.clone());
                        }
                    }
                }
                select(font, db)
            },
        ),
        select_fallback: usvg::FontResolver::default_fallback_selector(),
    }
}
#[doc = " Plain view of a `Color`."]
#[napi(object)]
#[derive(Clone)]
pub struct Color {
    pub red: u32,
    pub green: u32,
    pub blue: u32,
}
impl From<&usvg::Color> for Color {
    fn from(v: &usvg::Color) -> Self {
        Self {
            red: v.red.clone() as u32,
            green: v.green.clone() as u32,
            blue: v.blue.clone() as u32,
        }
    }
}
#[doc = " Read-only view of a `FaceInfo`."]
#[napi]
pub struct FontFace {
    inner: usvg::fontdb::FaceInfo,
}
impl FontFace {
    fn wrap(inner: usvg::fontdb::FaceInfo) -> Self {
        Self { inner }
    }
}
#[napi]
impl FontFace {
    #[napi(getter)]
    pub fn index(&self) -> u32 {
        let v = &self.inner;
        v.index.clone() as u32
    }
    #[napi(getter)]
    pub fn post_script_name(&self) -> String {
        let v = &self.inner;
        v.post_script_name.clone().to_string()
    }
    #[napi(getter)]
    pub fn weight(&self) -> u32 {
        let v = &self.inner;
        v.weight.clone().0 as u32
    }
    #[napi(getter)]
    pub fn monospaced(&self) -> bool {
        let v = &self.inner;
        v.monospaced.clone()
    }
}
#[doc = " Read-only view of a `Primitive`."]
#[napi]
pub struct Primitive {
    inner: usvg::filter::Primitive,
}
impl Primitive {
    fn wrap(inner: usvg::filter::Primitive) -> Self {
        Self { inner }
    }
}
#[napi]
impl Primitive {
    #[napi(getter)]
    pub fn rect(&self) -> BBox {
        let v = &self.inner;
        BBox::from(v.rect())
    }
    #[napi(getter)]
    pub fn color_interpolation(&self) -> ColorInterpolation {
        let v = &self.inner;
        ColorInterpolation::from(v.color_interpolation())
    }
    #[napi(getter)]
    pub fn result(&self) -> String {
        let v = &self.inner;
        v.result().to_string()
    }
}
#[doc = " Plain view of a `Stop`."]
#[napi(object)]
#[derive(Clone)]
pub struct Stop {
    pub offset: f64,
    pub color: Color,
    pub opacity: f64,
}
impl From<&usvg::Stop> for Stop {
    fn from(v: &usvg::Stop) -> Self {
        Self {
            offset: v.offset().get() as f64,
            color: Color::from(&v.color()),
            opacity: v.opacity().get() as f64,
        }
    }
}
#[doc = " Read-only handle on a `usvg::filter::Filter`."]
#[napi]
pub struct Filter {
    inner: std::sync::Arc<usvg::filter::Filter>,
}
impl Filter {
    fn wrap(inner: std::sync::Arc<usvg::filter::Filter>) -> Self {
        Self { inner }
    }
}
#[napi]
impl Filter {
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Filter region."]
    #[doc = ""]
    #[doc = " `x`, `y`, `width` and `height` in the SVG."]
    #[napi]
    pub fn rect(&self) -> BBox {
        BBox::from(self.inner.rect())
    }
    #[doc = " A list of filter primitives."]
    #[napi]
    pub fn primitives(&self) -> Vec<Primitive> {
        self.inner
            .primitives()
            .into_iter()
            .map(|x| Primitive::wrap(x.clone()))
            .collect()
    }
}
#[doc = " Read-only handle on a `usvg::RadialGradient`."]
#[napi]
pub struct RadialGradient {
    inner: std::sync::Arc<usvg::RadialGradient>,
}
impl RadialGradient {
    fn wrap(inner: std::sync::Arc<usvg::RadialGradient>) -> Self {
        Self { inner }
    }
}
#[napi]
impl RadialGradient {
    #[doc = " `cx` coordinate."]
    #[napi]
    pub fn cx(&self) -> f64 {
        self.inner.cx() as f64
    }
    #[doc = " `cy` coordinate."]
    #[napi]
    pub fn cy(&self) -> f64 {
        self.inner.cy() as f64
    }
    #[doc = " Gradient radius."]
    #[napi]
    pub fn r(&self) -> f64 {
        self.inner.r().get() as f64
    }
    #[doc = " `fx` coordinate."]
    #[napi]
    pub fn fx(&self) -> f64 {
        self.inner.fx() as f64
    }
    #[doc = " `fy` coordinate."]
    #[napi]
    pub fn fy(&self) -> f64 {
        self.inner.fy() as f64
    }
    #[doc = " Focal radius."]
    #[napi]
    pub fn fr(&self) -> f64 {
        self.inner.fr().get() as f64
    }
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Gradient transform."]
    #[doc = ""]
    #[doc = " `gradientTransform` in SVG."]
    #[napi]
    pub fn transform(&self) -> Matrix {
        Matrix::from(self.inner.transform())
    }
    #[doc = " Gradient spreading method."]
    #[doc = ""]
    #[doc = " `spreadMethod` in SVG."]
    #[napi]
    pub fn spread_method(&self) -> SpreadMethod {
        SpreadMethod::from(self.inner.spread_method())
    }
    #[doc = " A list of `stop` elements."]
    #[napi]
    pub fn stops(&self) -> Vec<Stop> {
        self.inner.stops().into_iter().map(Stop::from).collect()
    }
}
#[doc = " Read-only handle on a `usvg::Pattern`."]
#[napi]
pub struct Pattern {
    inner: std::sync::Arc<usvg::Pattern>,
}
impl Pattern {
    fn wrap(inner: std::sync::Arc<usvg::Pattern>) -> Self {
        Self { inner }
    }
}
#[napi]
impl Pattern {
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Pattern transform."]
    #[doc = ""]
    #[doc = " `patternTransform` in SVG."]
    #[napi]
    pub fn transform(&self) -> Matrix {
        Matrix::from(self.inner.transform())
    }
    #[doc = " Pattern rectangle."]
    #[doc = ""]
    #[doc = " `x`, `y`, `width` and `height` in SVG."]
    #[napi]
    pub fn rect(&self) -> BBox {
        BBox::from(self.inner.rect())
    }
}
impl HasRoot for usvg::Pattern {
    fn group(&self) -> &usvg::Group {
        self.root()
    }
}
#[napi]
impl Pattern {
    #[doc = " Children of this definition's content group."]
    #[napi]
    pub fn children(&self) -> Vec<SvgNode> {
        let base = NodeBase::Def(self.inner.clone());
        (0..self.inner.root().children().len())
            .map(|i| SvgNode {
                tree: None,
                base: base.clone(),
                path: vec![i as u32],
            })
            .collect()
    }
}
#[doc = " Read-only handle on a `usvg::Mask`."]
#[napi]
pub struct Mask {
    inner: std::sync::Arc<usvg::Mask>,
}
impl Mask {
    fn wrap(inner: std::sync::Arc<usvg::Mask>) -> Self {
        Self { inner }
    }
}
#[napi]
impl Mask {
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Mask rectangle."]
    #[doc = ""]
    #[doc = " `x`, `y`, `width` and `height` in SVG."]
    #[napi]
    pub fn rect(&self) -> BBox {
        BBox::from(self.inner.rect())
    }
    #[doc = " Mask type."]
    #[doc = ""]
    #[doc = " `mask-type` in SVG."]
    #[napi]
    pub fn kind(&self) -> MaskType {
        MaskType::from(self.inner.kind())
    }
}
impl HasRoot for usvg::Mask {
    fn group(&self) -> &usvg::Group {
        self.root()
    }
}
#[napi]
impl Mask {
    #[doc = " Children of this definition's content group."]
    #[napi]
    pub fn children(&self) -> Vec<SvgNode> {
        let base = NodeBase::Def(self.inner.clone());
        (0..self.inner.root().children().len())
            .map(|i| SvgNode {
                tree: None,
                base: base.clone(),
                path: vec![i as u32],
            })
            .collect()
    }
}
#[doc = " Read-only handle on a `usvg::LinearGradient`."]
#[napi]
pub struct LinearGradient {
    inner: std::sync::Arc<usvg::LinearGradient>,
}
impl LinearGradient {
    fn wrap(inner: std::sync::Arc<usvg::LinearGradient>) -> Self {
        Self { inner }
    }
}
#[napi]
impl LinearGradient {
    #[doc = " `x1` coordinate."]
    #[napi]
    pub fn x1(&self) -> f64 {
        self.inner.x1() as f64
    }
    #[doc = " `y1` coordinate."]
    #[napi]
    pub fn y1(&self) -> f64 {
        self.inner.y1() as f64
    }
    #[doc = " `x2` coordinate."]
    #[napi]
    pub fn x2(&self) -> f64 {
        self.inner.x2() as f64
    }
    #[doc = " `y2` coordinate."]
    #[napi]
    pub fn y2(&self) -> f64 {
        self.inner.y2() as f64
    }
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Gradient transform."]
    #[doc = ""]
    #[doc = " `gradientTransform` in SVG."]
    #[napi]
    pub fn transform(&self) -> Matrix {
        Matrix::from(self.inner.transform())
    }
    #[doc = " Gradient spreading method."]
    #[doc = ""]
    #[doc = " `spreadMethod` in SVG."]
    #[napi]
    pub fn spread_method(&self) -> SpreadMethod {
        SpreadMethod::from(self.inner.spread_method())
    }
    #[doc = " A list of `stop` elements."]
    #[napi]
    pub fn stops(&self) -> Vec<Stop> {
        self.inner.stops().into_iter().map(Stop::from).collect()
    }
}
#[doc = " Read-only handle on a `usvg::ClipPath`."]
#[napi]
pub struct ClipPath {
    inner: std::sync::Arc<usvg::ClipPath>,
}
impl ClipPath {
    fn wrap(inner: std::sync::Arc<usvg::ClipPath>) -> Self {
        Self { inner }
    }
}
#[napi]
impl ClipPath {
    #[doc = " Element's ID."]
    #[doc = ""]
    #[doc = " Taken from the SVG itself."]
    #[doc = " Used only during SVG writing. `resvg` doesn't rely on this property."]
    #[napi]
    pub fn id(&self) -> String {
        self.inner.id().to_string()
    }
    #[doc = " Clip path transform."]
    #[doc = ""]
    #[doc = " `transform` in SVG."]
    #[napi]
    pub fn transform(&self) -> Matrix {
        Matrix::from(self.inner.transform())
    }
}
impl HasRoot for usvg::ClipPath {
    fn group(&self) -> &usvg::Group {
        self.root()
    }
}
#[napi]
impl ClipPath {
    #[doc = " Children of this definition's content group."]
    #[napi]
    pub fn children(&self) -> Vec<SvgNode> {
        let base = NodeBase::Def(self.inner.clone());
        (0..self.inner.root().children().len())
            .map(|i| SvgNode {
                tree: None,
                base: base.clone(),
                path: vec![i as u32],
            })
            .collect()
    }
}
#[doc = " Which flavour of node this is."]
#[napi(string_enum = "camelCase")]
#[derive(Copy, Clone)]
pub enum NodeKind {
    Group,
    Path,
    Image,
    Text,
}
#[doc = " Walks a child-index path down from the root group."]
#[doc = " usvg and resvg report every recoverable problem through the `log` crate"]
#[doc = " -- unsupported elements, unparsable values, skipped images. Nothing"]
#[doc = " consumes it by default, so those messages are lost; this buffers them."]
static LOGS: std::sync::Mutex<Vec<String>> = std::sync::Mutex::new(Vec::new());
struct LogCollector;
static LOG_COLLECTOR: LogCollector = LogCollector;
impl log::Log for LogCollector {
    fn enabled(&self, _: &log::Metadata) -> bool {
        true
    }
    fn log(&self, record: &log::Record) {
        if let Ok(mut buf) = LOGS.lock() {
            if buf.len() < 500 {
                buf.push(format!(
                    "{} {}: {}",
                    record.level(),
                    record.target(),
                    record.args()
                ));
            }
        }
    }
    fn flush(&self) {}
}
#[doc = " Starts collecting what usvg and resvg report."]
#[doc = ""]
#[doc = " `level` is `off`, `error`, `warn`, `info`, `debug` or `trace`. Safe to"]
#[doc = " call repeatedly: the logger is installed once, the level always applies."]
#[napi]
pub fn set_log_level(level: String) -> Result<()> {
    let filter: log::LevelFilter = level
        .parse()
        .map_err(|_| Error::from_reason(format!("unknown log level: {level:?}")))?;
    static INSTALLED: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    INSTALLED.get_or_init(|| {
        let _ = log::set_logger(&LOG_COLLECTOR);
    });
    log::set_max_level(filter);
    Ok(())
}
#[doc = " Drains the messages collected since the last call."]
#[napi]
pub fn take_logs() -> Vec<String> {
    LOGS.lock()
        .map(|mut buf| std::mem::take(&mut *buf))
        .unwrap_or_default()
}
#[doc = " Anything that owns a content group: the document, or a def such as a"]
#[doc = " pattern, a mask or a clip path. The generator implements it for every"]
#[doc = " wrapped type that has a `root() -> &Group`."]
pub trait HasRoot {
    fn group(&self) -> &usvg::Group;
}
#[doc = " The strict policy drops `FaceInfo::families` -- it is a"]
#[doc = " `Vec<(String, Language)>`, and no rule maps a tuple with a language"]
#[doc = " tag. But fontdb queries by *family*, not by PostScript name, so"]
#[doc = " without this a caller cannot find the string to put in `fontFamily`."]
#[doc = " Decision: expose the names, drop the language tags."]
#[napi]
impl FontFace {
    #[doc = " Family names of this face, English (US) first when present."]
    #[napi(getter)]
    pub fn families(&self) -> Vec<String> {
        self.inner
            .families
            .iter()
            .map(|(name, _)| name.clone())
            .collect()
    }
}
#[doc = " Where a node path starts from."]
#[derive(Clone)]
enum NodeBase {
    Tree(std::sync::Arc<usvg::Tree>),
    Def(std::sync::Arc<dyn HasRoot>),
}
impl NodeBase {
    fn group(&self) -> &usvg::Group {
        match self {
            NodeBase::Tree(t) => t.root(),
            NodeBase::Def(d) => d.group(),
        }
    }
}
fn node_at<'t>(root: &'t usvg::Group, path: &[u32]) -> Option<&'t usvg::Node> {
    let (last, rest) = path.split_last()?;
    let mut group = root;
    for i in rest {
        match group.children().get(*i as usize)? {
            usvg::Node::Group(g) => group = g,
            _ => return None,
        }
    }
    group.children().get(*last as usize)
}
#[doc = " Depth-first search for an element id, returning its index path."]
fn path_of_id(group: &usvg::Group, id: &str, prefix: &mut Vec<u32>) -> Option<Vec<u32>> {
    for (i, child) in group.children().iter().enumerate() {
        prefix.push(i as u32);
        if child.id() == id {
            return Some(prefix.clone());
        }
        if let usvg::Node::Group(g) = child {
            if let Some(found) = path_of_id(g, id, prefix) {
                return Some(found);
            }
        }
        prefix.pop();
    }
    None
}
#[doc = " A read-only handle on one element of the parsed tree."]
#[doc = ""]
#[doc = " usvg stores nodes as `Box`, not `Arc`, so a handle cannot own one. It"]
#[doc = " keeps the tree alive plus the child-index path instead, and re-resolves"]
#[doc = " on each call -- safe because a parsed tree is immutable."]
#[napi]
pub struct SvgNode {
    #[doc = " The document, when there is one: a node reached through a def has"]
    #[doc = " no document context, so the def tables are out of reach from it."]
    tree: Option<std::sync::Arc<usvg::Tree>>,
    base: NodeBase,
    path: Vec<u32>,
}
impl SvgNode {
    fn node(&self) -> Result<&usvg::Node> {
        node_at(self.base.group(), &self.path)
            .ok_or_else(|| Error::from_reason("node path no longer resolves"))
    }
    fn child(&self, i: usize) -> Self {
        let mut path = self.path.clone();
        path.push(i as u32);
        Self {
            tree: self.tree.clone(),
            base: self.base.clone(),
            path,
        }
    }
}
#[napi]
impl SvgNode {
    #[doc = " `group`, `path`, `image` or `text`."]
    #[napi(getter)]
    pub fn kind(&self) -> Result<NodeKind> {
        Ok(match self.node()? {
            usvg::Node::Group(_) => NodeKind::Group,
            usvg::Node::Path(_) => NodeKind::Path,
            usvg::Node::Image(_) => NodeKind::Image,
            usvg::Node::Text(_) => NodeKind::Text,
        })
    }
    #[doc = " Direct children. Empty for anything that is not a group."]
    #[napi]
    pub fn children(&self) -> Result<Vec<SvgNode>> {
        let count = match self.node()? {
            usvg::Node::Group(g) => g.children().len(),
            _ => 0,
        };
        Ok((0..count).map(|i| self.child(i)).collect())
    }
    #[doc = " Extent of this element's own filters, if it is a filtered group."]
    #[doc = " This is what the document-level `filtersBoundingBox()` cannot see:"]
    #[doc = " usvg wraps every filtered element in an inner group."]
    #[napi]
    pub fn filters_bbox(&self) -> Result<Option<BBox>> {
        Ok(match self.node()? {
            usvg::Node::Group(g) => g.filters_bounding_box().map(BBox::from),
            _ => None,
        })
    }
    #[doc = " Extent this element will actually occupy once rendered, contours and"]
    #[doc = " filters included."]
    #[napi]
    pub fn extent(&self) -> Result<Option<BBox>> {
        Ok(node_extent(self.node()?).map(BBox::from))
    }
    #[doc = " Clip path applied to this element, if it is a clipped group."]
    #[doc = ""]
    #[doc = " usvg hands out a bare `&ClipPath` here, with no `Arc` to hold on to,"]
    #[doc = " so it is matched by `id` against the document's clip-path table."]
    #[doc = " Returns `null` for an unnamed clip path."]
    #[napi]
    pub fn clip_path(&self) -> Result<Option<ClipPath>> {
        let usvg::Node::Group(g) = self.node()? else {
            return Ok(None);
        };
        let Some(target) = g.clip_path() else {
            return Ok(None);
        };
        let Some(tree) = &self.tree else {
            return Ok(None);
        };
        Ok(tree
            .clip_paths()
            .iter()
            .find(|c| !target.id().is_empty() && c.id() == target.id())
            .cloned()
            .map(ClipPath::wrap))
    }
    #[doc = " Mask applied to this element, matched by `id` like `clipPath`."]
    #[napi]
    pub fn mask(&self) -> Result<Option<Mask>> {
        let usvg::Node::Group(g) = self.node()? else {
            return Ok(None);
        };
        let Some(target) = g.mask() else {
            return Ok(None);
        };
        let Some(tree) = &self.tree else {
            return Ok(None);
        };
        Ok(tree
            .masks()
            .iter()
            .find(|m| !target.id().is_empty() && m.id() == target.id())
            .cloned()
            .map(Mask::wrap))
    }
    #[doc = " Renders this element alone, sized to its own extent."]
    #[napi]
    pub fn render_png(&self, params: Option<RenderParams>) -> Result<Buffer> {
        render_node_png(self.node()?, &params.unwrap_or_default())
    }
    #[doc = " Returns node's ID."]
    #[napi]
    pub fn id(&self) -> Result<String> {
        let __n = self.node()?;
        Ok(__n.id().to_string())
    }
    #[doc = " Returns node's absolute transform."]
    #[doc = ""]
    #[doc = " This method is cheap since absolute transforms are already resolved."]
    #[napi]
    pub fn abs_transform(&self) -> Result<Matrix> {
        let __n = self.node()?;
        Ok(Matrix::from(__n.abs_transform()))
    }
    #[doc = " Returns node's bounding box in object coordinates, if any."]
    #[napi]
    pub fn bounding_box(&self) -> Result<BBox> {
        let __n = self.node()?;
        Ok(BBox::from(__n.bounding_box()))
    }
    #[doc = " Returns node's bounding box in canvas coordinates, if any."]
    #[napi]
    pub fn abs_bounding_box(&self) -> Result<BBox> {
        let __n = self.node()?;
        Ok(BBox::from(__n.abs_bounding_box()))
    }
    #[doc = " Returns node's bounding box, including stroke, in object coordinates, if any."]
    #[napi]
    pub fn stroke_bounding_box(&self) -> Result<BBox> {
        let __n = self.node()?;
        Ok(BBox::from(__n.stroke_bounding_box()))
    }
    #[doc = " Returns node's bounding box, including stroke, in canvas coordinates, if any."]
    #[napi]
    pub fn abs_stroke_bounding_box(&self) -> Result<BBox> {
        let __n = self.node()?;
        Ok(BBox::from(__n.abs_stroke_bounding_box()))
    }
    #[doc = " Element's \"layer\" bounding box in canvas units, if any."]
    #[doc = ""]
    #[doc = " For most nodes this is just `abs_bounding_box`,"]
    #[doc = " but for groups this is `abs_layer_bounding_box`."]
    #[doc = ""]
    #[doc = " See [`Group::layer_bounding_box`] for details."]
    #[napi]
    pub fn abs_layer_bounding_box(&self) -> Result<Option<BBox>> {
        let __n = self.node()?;
        Ok(__n.abs_layer_bounding_box().map(BBox::from))
    }
}
#[doc = " A parsed SVG, ready to be rendered any number of times."]
#[napi]
pub struct Resvg {
    tree: std::sync::Arc<usvg::Tree>,
    #[doc = " Source kept verbatim: resolving an image means re-parsing."]
    svg: Vec<u8>,
    options: RenderOptions,
    fonts: std::sync::Arc<usvg::fontdb::Database>,
    images: ImageMap,
    pending_images: Vec<String>,
    pending_fonts: Vec<String>,
}
#[napi]
impl Resvg {
    #[napi(constructor)]
    pub fn new(
        svg: Either<String, Buffer>,
        options: Option<RenderOptions>,
        fonts: Option<&FontDatabase>,
        images: Option<std::collections::HashMap<String, Buffer>>,
    ) -> Result<Self> {
        let svg = match svg {
            Either::A(text) => text.into_bytes(),
            Either::B(data) => data.to_vec(),
        };
        let options = options.unwrap_or_default();
        let fonts = match fonts {
            Some(f) => std::sync::Arc::new(f.inner.clone()),
            None => default_fontdb(),
        };
        let images: ImageMap = images
            .unwrap_or_default()
            .into_iter()
            .map(|(href, buf)| (href, std::sync::Arc::new(buf.to_vec())))
            .collect();
        let (tree, pending_images, pending_fonts) =
            Self::build(&svg, &options, fonts.clone(), &images)?;
        Ok(Self {
            tree: std::sync::Arc::new(tree),
            svg,
            options,
            fonts,
            images,
            pending_images,
            pending_fonts,
        })
    }
    #[doc = " Hrefs of `<image>` elements that neither the supplied buffers nor the"]
    #[doc = " filesystem could resolve. Feed them back with `resolveImage`."]
    #[napi]
    pub fn pending_images(&self) -> Vec<String> {
        self.pending_images.clone()
    }
    #[doc = " Named font families requested by `<text>` that the database does not"]
    #[doc = " carry, so the text was rendered with a fallback face. Load them with"]
    #[doc = " `FontDatabase` and re-parse to fix the output."]
    #[napi]
    pub fn pending_fonts(&self) -> Vec<String> {
        self.pending_fonts.clone()
    }
    #[doc = " Supplies one image and re-parses the document."]
    #[doc = ""]
    #[doc = " Pass everything you already have through the constructor's `images`"]
    #[doc = " argument instead: this re-parses once per call."]
    #[napi]
    pub fn resolve_image(&mut self, href: String, data: Buffer) -> Result<()> {
        self.images.insert(href, std::sync::Arc::new(data.to_vec()));
        let (tree, pending_images, pending_fonts) =
            Self::build(&self.svg, &self.options, self.fonts.clone(), &self.images)?;
        self.tree = std::sync::Arc::new(tree);
        self.pending_images = pending_images;
        self.pending_fonts = pending_fonts;
        Ok(())
    }
    #[napi(getter)]
    pub fn width(&self) -> f64 {
        self.tree.size().width() as f64
    }
    #[napi(getter)]
    pub fn height(&self) -> f64 {
        self.tree.size().height() as f64
    }
    #[doc = " Renders to a PNG buffer."]
    #[napi]
    pub fn render_png(&self, params: Option<RenderParams>) -> Result<Buffer> {
        let pixmap = self.draw(params.unwrap_or_default())?;
        pixmap
            .encode_png()
            .map(Buffer::from)
            .map_err(|e| Error::from_reason(format!("PNG encoding failed: {e}")))
    }
    #[doc = " Renders to a PNG buffer on a worker thread. Rasterising and PNG"]
    #[doc = " encoding both happen off the event loop."]
    #[napi(ts_return_type = "Promise<Buffer>")]
    pub fn render_png_async(
        &self,
        params: Option<RenderParams>,
        signal: Option<AbortSignal>,
    ) -> AsyncTask<PngTask> {
        AsyncTask::with_optional_signal(
            PngTask {
                tree: self.tree.clone(),
                params: params.unwrap_or_default(),
            },
            signal,
        )
    }
    #[doc = " Renders to raw RGBA8 pixels on a worker thread."]
    #[napi(ts_return_type = "Promise<RawImage>")]
    pub fn render_raw_async(
        &self,
        params: Option<RenderParams>,
        signal: Option<AbortSignal>,
    ) -> AsyncTask<RawTask> {
        AsyncTask::with_optional_signal(
            RawTask {
                tree: self.tree.clone(),
                params: params.unwrap_or_default(),
            },
            signal,
        )
    }
    #[doc = " Parses on a worker thread. Same arguments as the constructor, and the"]
    #[doc = " resolved instance still reports `pendingImages` / `pendingFonts`."]
    #[napi(ts_return_type = "Promise<Resvg>")]
    pub fn parse_async(
        svg: Either<String, Buffer>,
        options: Option<RenderOptions>,
        fonts: Option<&FontDatabase>,
        images: Option<std::collections::HashMap<String, Buffer>>,
        signal: Option<AbortSignal>,
    ) -> AsyncTask<ParseTask> {
        AsyncTask::with_optional_signal(
            ParseTask {
                svg: match svg {
                    Either::A(text) => text.into_bytes(),
                    Either::B(data) => data.to_vec(),
                },
                options: options.unwrap_or_default(),
                fonts: match fonts {
                    Some(f) => std::sync::Arc::new(f.inner.clone()),
                    None => default_fontdb(),
                },
                images: images
                    .unwrap_or_default()
                    .into_iter()
                    .map(|(href, buf)| (href, std::sync::Arc::new(buf.to_vec())))
                    .collect(),
            },
            signal,
        )
    }
    #[doc = " Bounding box of one element, by `id`, as it will be rendered"]
    #[doc = " (contours, filters and transforms included). `null` if there is no"]
    #[doc = " such id or the element has no visible size."]
    #[napi]
    pub fn node_bbox(&self, id: String) -> Option<BBox> {
        self.tree
            .node_by_id(&id)
            .and_then(node_extent)
            .map(BBox::from)
    }
    #[doc = " Renders a single element, by `id`, into its own PNG -- the output is"]
    #[doc = " sized to that element, not to the document. Useful to slice an icon"]
    #[doc = " out of a sprite sheet."]
    #[napi]
    pub fn render_node_png(&self, id: String, params: Option<RenderParams>) -> Result<Buffer> {
        let node = self
            .tree
            .node_by_id(&id)
            .ok_or_else(|| Error::from_reason(format!("no element with id {id:?}")))?;
        render_node_png(node, &params.unwrap_or_default())
    }
    #[doc = " Handle on one element, by `id`."]
    #[napi]
    pub fn node(&self, id: String) -> Option<SvgNode> {
        path_of_id(self.tree.root(), &id, &mut Vec::new()).map(|path| SvgNode {
            tree: Some(self.tree.clone()),
            base: NodeBase::Tree(self.tree.clone()),
            path,
        })
    }
    #[doc = " Direct children of the root group."]
    #[napi]
    pub fn children(&self) -> Vec<SvgNode> {
        (0..self.tree.root().children().len())
            .map(|i| SvgNode {
                tree: Some(self.tree.clone()),
                base: NodeBase::Tree(self.tree.clone()),
                path: vec![i as u32],
            })
            .collect()
    }
    #[doc = " Image size."]
    #[doc = ""]
    #[doc = " Size of an image that should be created to fit the SVG."]
    #[doc = ""]
    #[doc = " `width` and `height` in SVG."]
    #[doc = ""]
    #[doc = " Note that this does not necessarily represent the bounding box of the"]
    #[doc = " rendered contents. Use"]
    #[doc = " [`self.root().abs_layer_bounding_box()`](Group::abs_layer_bounding_box)"]
    #[doc = " to retrieve it instead."]
    #[napi]
    pub fn size(&self) -> Dimensions {
        Dimensions::from(self.tree.size())
    }
    #[doc = " Checks if the current tree has any text nodes."]
    #[napi]
    pub fn has_text_nodes(&self) -> bool {
        self.tree.has_text_nodes()
    }
    #[doc = " Checks if the current tree has any `defs` nodes."]
    #[napi]
    pub fn has_defs_nodes(&self) -> bool {
        self.tree.has_defs_nodes()
    }
    #[doc = " Returns a list of all unique [`LinearGradient`]s in the tree."]
    #[napi]
    pub fn linear_gradients(&self) -> Vec<LinearGradient> {
        self.tree
            .linear_gradients()
            .iter()
            .cloned()
            .map(LinearGradient::wrap)
            .collect()
    }
    #[doc = " Returns a list of all unique [`RadialGradient`]s in the tree."]
    #[napi]
    pub fn radial_gradients(&self) -> Vec<RadialGradient> {
        self.tree
            .radial_gradients()
            .iter()
            .cloned()
            .map(RadialGradient::wrap)
            .collect()
    }
    #[doc = " Returns a list of all unique [`Pattern`]s in the tree."]
    #[napi]
    pub fn patterns(&self) -> Vec<Pattern> {
        self.tree
            .patterns()
            .iter()
            .cloned()
            .map(Pattern::wrap)
            .collect()
    }
    #[doc = " Returns a list of all unique [`ClipPath`]s in the tree."]
    #[napi]
    pub fn clip_paths(&self) -> Vec<ClipPath> {
        self.tree
            .clip_paths()
            .iter()
            .cloned()
            .map(ClipPath::wrap)
            .collect()
    }
    #[doc = " Returns a list of all unique [`Mask`]s in the tree."]
    #[napi]
    pub fn masks(&self) -> Vec<Mask> {
        self.tree.masks().iter().cloned().map(Mask::wrap).collect()
    }
    #[doc = " Returns a list of all unique [`Filter`](filter::Filter)s in the tree."]
    #[napi]
    pub fn filters(&self) -> Vec<Filter> {
        self.tree
            .filters()
            .iter()
            .cloned()
            .map(Filter::wrap)
            .collect()
    }
    #[doc = " Returns the font database that applies to all text nodes in the tree."]
    #[napi]
    pub fn fontdb(&self) -> FontDatabase {
        FontDatabase::wrap(self.tree.fontdb().clone())
    }
    #[doc = " Element's transform."]
    #[doc = ""]
    #[doc = " This is a relative transform. The one that is set via the `transform` attribute in SVG."]
    #[napi]
    pub fn transform(&self) -> Matrix {
        Matrix::from(self.tree.root().transform())
    }
    #[doc = " Element's absolute transform."]
    #[doc = ""]
    #[doc = " Contains all ancestors transforms including group's transform."]
    #[doc = ""]
    #[doc = " Note that subroots, like clipPaths, masks and patterns, have their own root transform,"]
    #[doc = " which isn't affected by the node that references this subroot."]
    #[napi]
    pub fn abs_transform(&self) -> Matrix {
        Matrix::from(self.tree.root().abs_transform())
    }
    #[doc = " Group opacity."]
    #[doc = ""]
    #[doc = " After the group is rendered we should combine"]
    #[doc = " it with a parent group using the specified opacity."]
    #[napi]
    pub fn opacity(&self) -> f64 {
        self.tree.root().opacity().get() as f64
    }
    #[doc = " Group blend mode."]
    #[doc = ""]
    #[doc = " `mix-blend-mode` in SVG."]
    #[napi]
    pub fn blend_mode(&self) -> BlendMode {
        BlendMode::from(self.tree.root().blend_mode())
    }
    #[doc = " Element's object bounding box."]
    #[doc = ""]
    #[doc = " `objectBoundingBox` in SVG terms. Meaning it doesn't affected by parent transforms."]
    #[doc = ""]
    #[doc = " Can be set to `None` in case of an empty group."]
    #[napi]
    pub fn bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().bounding_box())
    }
    #[doc = " Element's bounding box in canvas coordinates."]
    #[doc = ""]
    #[doc = " `userSpaceOnUse` in SVG terms."]
    #[napi]
    pub fn abs_bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().abs_bounding_box())
    }
    #[doc = " Element's object bounding box including stroke."]
    #[doc = ""]
    #[doc = " Similar to `bounding_box`, but includes stroke."]
    #[napi]
    pub fn stroke_bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().stroke_bounding_box())
    }
    #[doc = " Element's bounding box including stroke in user coordinates."]
    #[doc = ""]
    #[doc = " Similar to `abs_bounding_box`, but includes stroke."]
    #[napi]
    pub fn abs_stroke_bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().abs_stroke_bounding_box())
    }
    #[doc = " Element's \"layer\" bounding box in object units."]
    #[doc = ""]
    #[doc = " Conceptually, this is `stroke_bounding_box` expanded and/or clipped"]
    #[doc = " by `filters_bounding_box`, but also including all the children."]
    #[doc = " This is the bounding box `resvg` will later use to allocate layers/pixmaps"]
    #[doc = " during isolated groups rendering."]
    #[doc = ""]
    #[doc = " Only groups have it, because only groups can have filters."]
    #[doc = " For other nodes layer bounding box is the same as stroke bounding box."]
    #[doc = ""]
    #[doc = " Unlike other bounding boxes, cannot have zero size."]
    #[doc = ""]
    #[doc = " Returns 0x0x1x1 for empty groups."]
    #[napi]
    pub fn layer_bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().layer_bounding_box())
    }
    #[doc = " Element's \"layer\" bounding box in canvas units."]
    #[napi]
    pub fn abs_layer_bounding_box(&self) -> BBox {
        BBox::from(self.tree.root().abs_layer_bounding_box())
    }
    #[doc = " Returns `true` if the group has any children."]
    #[napi]
    pub fn has_children(&self) -> bool {
        self.tree.root().has_children()
    }
    #[doc = " Calculates a node's filter bounding box."]
    #[doc = ""]
    #[doc = " Filters with `objectBoundingBox` and missing or zero `bounding_box` would be ignored."]
    #[doc = ""]
    #[doc = " Note that a filter region can act like a clipping rectangle,"]
    #[doc = " therefore this function can produce a bounding box smaller than `bounding_box`."]
    #[doc = ""]
    #[doc = " Returns `None` when then group has no filters."]
    #[doc = ""]
    #[doc = " This function is very fast, that's why we do not store this bbox as a `Group` field."]
    #[napi]
    pub fn filters_bounding_box(&self) -> Option<BBox> {
        self.tree.root().filters_bounding_box().map(BBox::from)
    }
    #[doc = " Writes the parsed tree back out as a usvg-simplified SVG string."]
    #[doc = ""]
    #[doc = " Text is converted to paths unless `preserveText` is set."]
    #[napi(js_name = "toString")]
    pub fn to_svg_string(&self, options: Option<WriteOptions>) -> Result<String> {
        let opt = options.unwrap_or_default().to_usvg();
        let tree = &self.tree;
        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            usvg::Tree::to_string(tree, &opt)
        }))
        .map_err(|_| Error::from_reason("usvg panicked while writing the SVG"))
    }
    #[doc = " Renders to raw RGBA8 pixels."]
    #[napi]
    pub fn render_raw(&self, params: Option<RenderParams>) -> Result<RawImage> {
        let pixmap = self.draw(params.unwrap_or_default())?;
        let (width, height) = (pixmap.width(), pixmap.height());
        Ok(RawImage {
            width,
            height,
            data: Buffer::from(pixmap.take_demultiplied()),
        })
    }
}
impl Resvg {
    fn build(
        svg: &[u8],
        options: &RenderOptions,
        fonts: std::sync::Arc<usvg::fontdb::Database>,
        images: &ImageMap,
    ) -> Result<(usvg::Tree, Vec<String>, Vec<String>)> {
        let missing_images = Misses::default();
        let missing_fonts = Misses::default();
        let mut opts = options.to_usvg(fonts);
        opts.image_href_resolver = href_resolver(images.clone(), missing_images.clone());
        opts.font_resolver = font_resolver(missing_fonts.clone());
        let tree = usvg::Tree::from_data(svg, &opts)
            .map_err(|e| Error::from_reason(format!("invalid SVG: {e}")))?;
        Ok((
            tree,
            std::mem::take(&mut *missing_images.0.lock().unwrap()),
            std::mem::take(&mut *missing_fonts.0.lock().unwrap()),
        ))
    }
    fn draw(&self, p: RenderParams) -> Result<tiny_skia::Pixmap> {
        draw(&self.tree, &p)
    }
}
fn draw(tree: &usvg::Tree, p: &RenderParams) -> Result<tiny_skia::Pixmap> {
    let size = tree.size();
    let (base_w, base_h, off_x, off_y) = match &p.crop {
        Some(c) => (c.width as f32, c.height as f32, c.x as f32, c.y as f32),
        None => (size.width(), size.height(), 0.0, 0.0),
    };
    if !(base_w > 0.0 && base_h > 0.0) {
        return Err(Error::from_reason(format!("empty crop: {base_w}x{base_h}")));
    }
    let scale = if let Some(w) = p.width {
        w as f32 / base_w
    } else if let Some(h) = p.height {
        h as f32 / base_h
    } else {
        p.scale.unwrap_or(1.0) as f32
    };
    if !(scale.is_finite() && scale > 0.0) {
        return Err(Error::from_reason(format!("invalid scale: {scale}")));
    }
    let w = (base_w * scale).ceil() as u32;
    let h = (base_h * scale).ceil() as u32;
    let mut pixmap = tiny_skia::Pixmap::new(w, h)
        .ok_or_else(|| Error::from_reason(format!("bad pixmap size {w}x{h}")))?;
    if let Some(css) = &p.background {
        let c: svgtypes::Color = css
            .parse()
            .map_err(|_| Error::from_reason(format!("invalid background: {css}")))?;
        pixmap.fill(tiny_skia::Color::from_rgba8(
            c.red, c.green, c.blue, c.alpha,
        ));
    }
    resvg::render(
        tree,
        tiny_skia::Transform::from_scale(scale, scale).pre_translate(-off_x, -off_y),
        &mut pixmap.as_mut(),
    );
    Ok(pixmap)
}
#[doc = " Shared by `Resvg.renderNodePng` and `SvgNode.renderPng`."]
fn render_node_png(node: &usvg::Node, p: &RenderParams) -> Result<Buffer> {
    let bbox =
        node_extent(node).ok_or_else(|| Error::from_reason("element has no visible size"))?;
    let inner = node
        .abs_layer_bounding_box()
        .ok_or_else(|| Error::from_reason("element is empty"))?;
    let scale = if let Some(w) = p.width {
        w as f32 / bbox.width()
    } else if let Some(h) = p.height {
        h as f32 / bbox.height()
    } else {
        p.scale.unwrap_or(1.0) as f32
    };
    if !(scale.is_finite() && scale > 0.0) {
        return Err(Error::from_reason(format!("invalid scale: {scale}")));
    }
    let w = (bbox.width() * scale).ceil() as u32;
    let h = (bbox.height() * scale).ceil() as u32;
    let mut pixmap = tiny_skia::Pixmap::new(w, h)
        .ok_or_else(|| Error::from_reason(format!("bad pixmap size {w}x{h}")))?;
    if let Some(css) = &p.background {
        let c: svgtypes::Color = css
            .parse()
            .map_err(|_| Error::from_reason(format!("invalid background: {css}")))?;
        pixmap.fill(tiny_skia::Color::from_rgba8(
            c.red, c.green, c.blue, c.alpha,
        ));
    }
    resvg::render_node(
        node,
        tiny_skia::Transform::from_scale(scale, scale)
            .pre_translate(-bbox.x(), -bbox.y())
            .pre_concat(node.abs_transform())
            .pre_translate(inner.x(), inner.y()),
        &mut pixmap.as_mut(),
    )
    .ok_or_else(|| Error::from_reason("element is empty"))?;
    pixmap
        .encode_png()
        .map(Buffer::from)
        .map_err(|e| Error::from_reason(format!("PNG encoding failed: {e}")))
}
#[doc = " Rendered extent of a node."]
#[doc = ""]
#[doc = " `Node::abs_layer_bounding_box` gives a Group its full layer box but"]
#[doc = " hands back only the *geometric* box for a Path or Text, which would"]
#[doc = " clip the stroke, so widen those here."]
fn node_extent(node: &usvg::Node) -> Option<usvg::NonZeroRect> {
    match node {
        usvg::Node::Group(g) => Some(g.abs_layer_bounding_box()),
        usvg::Node::Path(p) => p.abs_stroke_bounding_box().to_non_zero_rect(),
        usvg::Node::Text(t) => t.abs_stroke_bounding_box().to_non_zero_rect(),
        usvg::Node::Image(i) => i.abs_bounding_box().to_non_zero_rect(),
    }
}
#[doc = " Rasterise + PNG encode on a libuv worker thread."]
pub struct PngTask {
    tree: std::sync::Arc<usvg::Tree>,
    params: RenderParams,
}
impl Task for PngTask {
    type Output = Vec<u8>;
    type JsValue = Buffer;
    fn compute(&mut self) -> Result<Self::Output> {
        draw(&self.tree, &self.params)?
            .encode_png()
            .map_err(|e| Error::from_reason(format!("PNG encoding failed: {e}")))
    }
    fn resolve(&mut self, _: napi::Env, png: Self::Output) -> Result<Self::JsValue> {
        Ok(Buffer::from(png))
    }
}
#[doc = " Rasterise on a libuv worker thread, no encoding."]
pub struct RawTask {
    tree: std::sync::Arc<usvg::Tree>,
    params: RenderParams,
}
impl Task for RawTask {
    type Output = (u32, u32, Vec<u8>);
    type JsValue = RawImage;
    fn compute(&mut self) -> Result<Self::Output> {
        let pixmap = draw(&self.tree, &self.params)?;
        let (w, h) = (pixmap.width(), pixmap.height());
        Ok((w, h, pixmap.take_demultiplied()))
    }
    fn resolve(&mut self, _: napi::Env, out: Self::Output) -> Result<Self::JsValue> {
        let (width, height, data) = out;
        Ok(RawImage {
            width,
            height,
            data: Buffer::from(data),
        })
    }
}
#[doc = " Parse on a libuv worker thread, resolving to a ready `Resvg`."]
pub struct ParseTask {
    svg: Vec<u8>,
    options: RenderOptions,
    fonts: std::sync::Arc<usvg::fontdb::Database>,
    images: ImageMap,
}
impl Task for ParseTask {
    type Output = (usvg::Tree, Vec<String>, Vec<String>);
    type JsValue = Resvg;
    fn compute(&mut self) -> Result<Self::Output> {
        Resvg::build(&self.svg, &self.options, self.fonts.clone(), &self.images)
    }
    fn resolve(&mut self, _: napi::Env, out: Self::Output) -> Result<Self::JsValue> {
        let (tree, pending_images, pending_fonts) = out;
        Ok(Resvg {
            tree: std::sync::Arc::new(tree),
            svg: std::mem::take(&mut self.svg),
            options: self.options.clone(),
            fonts: self.fonts.clone(),
            images: std::mem::take(&mut self.images),
            pending_images,
            pending_fonts,
        })
    }
}
#[doc = " Parse, rasterise and PNG-encode in one worker-thread round trip."]
pub struct RenderTask {
    svg: Vec<u8>,
    options: RenderOptions,
    params: RenderParams,
}
impl Task for RenderTask {
    type Output = Vec<u8>;
    type JsValue = Buffer;
    fn compute(&mut self) -> Result<Self::Output> {
        let (tree, _, _) =
            Resvg::build(&self.svg, &self.options, default_fontdb(), &ImageMap::new())?;
        draw(&tree, &self.params)?
            .encode_png()
            .map_err(|e| Error::from_reason(format!("PNG encoding failed: {e}")))
    }
    fn resolve(&mut self, _: napi::Env, png: Self::Output) -> Result<Self::JsValue> {
        Ok(Buffer::from(png))
    }
}
#[doc = " One-shot: parse and render a PNG entirely off the event loop."]
#[doc = ""]
#[doc = " Uses the process-wide system font database and resolves images off the"]
#[doc = " filesystem only. For a custom `FontDatabase`, supplied image buffers or"]
#[doc = " the `pendingImages` / `pendingFonts` reports, use `Resvg.parseAsync`."]
#[napi(ts_return_type = "Promise<Buffer>")]
pub fn render_async(
    svg: Either<String, Buffer>,
    options: Option<RenderOptions>,
    params: Option<RenderParams>,
    signal: Option<AbortSignal>,
) -> AsyncTask<RenderTask> {
    AsyncTask::with_optional_signal(
        RenderTask {
            svg: match svg {
                Either::A(text) => text.into_bytes(),
                Either::B(data) => data.to_vec(),
            },
            options: options.unwrap_or_default(),
            params: params.unwrap_or_default(),
        },
        signal,
    )
}
